### ISSUE TITLE
TSAN data race

### ISSUE THREAD

**Issue by wtholliday** [AudioKit/AudioKit#2814] opened 2023-01-01 22:22 UTC
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/841144/210186234-6928f4ca-530c-46b5-b87a-63a2d27d33c4.png">

To reproduce, run tests with TSAN enabled

@josi

**Comment by jcavar** [comment] 2023-01-08 09:16
The problem here is that tap callback is called on some internal queue.

#2815 should fix this, but I am not sure if it should be merged to be honest.

I think it is probably a better idea to rewrite a tap so that all synchronisation is performed on given (or default) dispatch queue.

**Comment by emurray2** [comment] 2023-01-08 09:19
> The problem here is that tap callback is called on some internal queue.
> 
> #2815 should fix this, but I am not sure if it should be merged to be honest.
> 
> I think it is probably a better idea to rewrite a tap so that all synchronisation is performed on given (or default) dispatch queue.

It looks like maybe this was already done in 799275688f6c5089492d04cf3885d5389058c00c

**Comment by jcavar** [comment] 2023-01-08 13:17
I think we should try to avoid dispatching on the main queue from the framework. 

In case of e.g. AmplitudeTap, calculation will be happening on the main queue, which might not be desirable. 

If framework does things on the main queue, you have no choice as a consumer. If it doesn’t, and you need it, it is easy to switch to main queue as a consumer. 

But, putting that aside, I don’t think this solves it either. You might be doing operations on the tap from another queue (as we do).

**Comment by wtholliday** [comment] 2023-01-08 19:06
If you don't dispatch from the main queue, the user will have to handle thread safety. Most users won't know, and they'll end up with bugs. AK should err on the side of safety.

I tried to implement the v6 taps using async/await (which would be safe I think) but there's no way of guaranteeing that the async callbacks are executed in the correct order AFAICT (see https://forums.swift.org/t/task-is-order-of-task-execution-deterministic/51553)

**Comment by jcavar** [comment] 2023-01-08 20:30
> If you don't dispatch from the main queue, the user will have to handle thread safety

This is under assumption that user is performing other tap operations on main queue.  Also, just to challenge this point, I thing there is balance to strike here:

If you run it on the main queue, users might end up with performance problems. And this is what happened to us in earlier version of tap. We have multiple taps around and all of them were doing their work on main queue. We had no way to dispatch this work on some other queue.

But my "proper" idea was to have an internal queue that will ensure thread safety of the tap, so users wouldn't need to worry about thread safety. That way, users would just need to dispatch back to main if they are updating UI.

> AK should err on the side of safety

I guess the simple thing to do here is to make callback queue argument default to `DispatchQueue.main`. Although I don't like it, as it is then easy to overlook it. This way, we force users to think were they want tap work to happen

> Not to belabor the point, but you didn't get it right either, because you didn't run TSAN.

Do you mean before or now? I did run it with TSAN, and I've tried again and I don't see any warnings being raised. Are you seeing something different?


> I tried to implement the v6 taps using async/await (which would be safe I think) but there's no way of guaranteeing that the async callbacks are executed in the correct order AFAICT (see https://forums.swift.org/t/task-is-order-of-task-execution-deterministic/51553)

I might be missing something here, but it seems to me that v6 tap doesn't have race condition even without `DispatchQueue.main` call?

The tricky part with the old tap is synchronisation between `stop`, `start` and callback calls. In the new implementation, we only have `tapBlock` in play (which I guess will become nullable?). When you don't need a tap, you just set it to nil. It is single writer single reader case with only one (atomic?) property?

**Comment by wtholliday** [comment] 2023-01-08 20:43
> If you run it on the main queue, users might end up with performance problems.

Yes they might, if they tend to block their main queue. Then they have other issues to fix and it's not our problem :)

> But my "proper" idea was to have an internal queue that will ensure thread safety of the tap, so users wouldn't need to worry about thread safety. That way, users would just need to dispatch back to main if they are updating UI.

Uses would have to worry about thread safety in that case because their callback is called from the queue's thread.

> Do you mean before or now? I did run it with TSAN, and I've tried again and I don't see any warnings being raised. Are you seeing something different?

I mean earlier, hence this bug. My point is that it's easy to make such a mistake. Thread safety is tricky.

> I might be missing something here, but it seems to me that v6 tap doesn't have race condition even without `DispatchQueue.main` call?

It's creating a thread for each tap (which is probably not a great idea anyway but that's a separate issue). Calling the tapBlock from the thread would offer no protection for the client.

> When you don't need a tap, you just set it to nil. It is single writer single reader case with only one (atomic?) property?

I haven't thought about how to turn off the tap (other than remove the whole node)

**Comment by jcavar** [comment] 2023-01-08 20:54
> Yes they might, if they tend to block their main queue. Then they have other issues to fix and it's not our problem :)

I am not sure I understand your argument? The point that I am making is that, if we hardcode the main queue as a callback for the tap, all the DSP in e.g. `AmplitudeTap` will be happening on the main queue. There is no way to avoid this as a consumer of the framework. And I think this is generally not desirable.

> Uses would have to worry about thread safety in that case because their callback is called from the queue's thread.

I am not sure if understand this point completely, but callback being called on a thread other then main is common pattern in Apple APIs. I think it is reasonable to design an API in such a way. It is very easy to catch this problem if you are updating UI from incorrect thread.

> I mean earlier, hence this bug. My point is that it's easy to make such a mistake. Thread safety is tricky.

I see, yes, and I agree. But I don't think adding dispatch on main solves this problem.

> It's creating a thread for each tap (which is probably not a great idea anyway but that's a separate issue). Calling the tapBlock from the thread would offer no protection for the client.

Protection agains what? I think the problem is internal consistency of the tap, which seems ok to me in v6 version.

**Comment by wtholliday** [comment] 2023-01-09 07:10
> Protection against what?

Data races, etc.

It's unfortunate that we can't solve this with async/await, because that would provide an elegant API. Instead we'd be optionally passing in a queue to call on, which is kinda gross.

AK is supposed to be beginner-friendly, and given AKs own developers struggle with data races (not picking on you here... there have been lots of data races), my goal is to keep things simple.

So that would mean

```
Tap(input) { samples
   ... do whatever with samples including update the UI
}
```

instead of:

```
Tap(input) { samples
   Task { // gotta know to do this otherwise gonna have data races, mysterious bugs, etc.
      MainActor.run {
          ... update the UI or other stuff
    }
   }
}
```

(or there's the older GCD way)

If you need to do a lot of processing on the samples returned by a tap, you could create a Task.

I know Apple APIs call your callbacks on whatever random thread and I think it's kinda gross.

**Comment by jcavar** [comment] 2023-01-09 07:44
> If you need to do a lot of processing on the samples returned by a tap, you could create a Task.

The problem is not processing after the tap, but the processing in the tap. `AmplitudeTap` would receive `doHandleTapBlock` on the main queue and as a consumer you would not be able to do anything about it.

I think passing `DispatchQueue` and making it default to `DispatchQueue.main` would achieve the API that you would like by default, and still allow consumer to customise it if needed.

> It's unfortunate that we can't solve this with async/await, because that would provide an elegant API. Instead we'd be optionally passing in a queue to call on, which is kinda gross.

I agree this would be the best design. It seems like it should be possible with AsyncStream API. I think your initial attempt made `tabBlock` async, but I think we need something like:

```
class Tap {
    func start() -> AsyncStream<Sample>
}
```

```
let tap = Tap(input)
let stream = tap.start()
for await value in stream { ... }
```

**Comment by wtholliday** [comment] 2023-01-09 19:01
> The problem is not processing after the tap, but the processing in the tap. `AmplitudeTap` would receive `doHandleTapBlock` on the main queue and as a consumer you would not be able to do anything about it.

That's changing in v6. There's no point in having a hierarchy of tap classes. The v6 tap just gives you samples and we provide some functions (or classes) that help with analysis.

> AsyncStream API

That looks promising.

What do you think about simplifying the API so the Tap just has to be polled?

```
class Tap {
    func getData() -> [[Float]]
}
```

`getData` would be safe to call from any thread. That's essentially what I do in my own app instead of callbacks.

**Comment by jcavar** [comment] 2023-01-10 19:08
> That's changing in v6. There's no point in having a hierarchy of tap classes. The v6 tap just gives you samples and we provide some functions (or classes) that help with analysis.

What will be equivalent way of getting amplitude in v6?

> What do you think about simplifying the API so the Tap just has to be polled?

Is this going to make it easy to miss samples? You would need to synchronise polling interval with how big ring buffer is and how big buffer size is?

**Comment by aure** [comment] 2023-01-10 19:12
These are good points that we're wrestling with. v6 taps are still evolving. They'll be good!

**Comment by wtholliday** [comment] 2023-01-10 19:49
> Is this going to make it easy to miss samples? You would need to synchronise polling interval with how big ring buffer is and how big buffer size is?

Yeah gotta keep up! In many cases (like something driving visuals) you don't really need to be very precise.

We would make the ring buffer relatively big and send a sample number along with the data so the client can tell if they've missed anything

**Closed** 2023-01-30 00:45 UTC
Labels: bug
