### ISSUE TITLE
Headset pluggin problem

### ISSUE THREAD

**Issue by 690858187** [AudioKit/AudioKit#1747] opened 2019-04-15 03:17 UTC
```
do {
            try AKSettings.setSession(category: .playback)
            AKSettings.playbackWhileMuted = true;
            try AVAudioSession.sharedInstance().setActive(true, options: .notifyOthersOnDeactivation)
        } catch {
            print(error)
        }
```

**Comment by aure** [comment] 2019-04-15 08:28
Original Title: AVAudioSession相同的配置，但是当拔插耳机EZAudioPlayer是正常的，AKPlayer和AKAudioPlayer都不正常,AKPlayer和AKAudioPlayer打印状态是playing,但是没有声音播放。我看stackoverflow有人问这个问题，但是没人给出解决答案。。。为什么会出现这种情况？

Translation: AVAudioSession has the same configuration, but when the plug-in headset EZAudioPlayer is normal, AKPlayer and AKAudioPlayer are not normal, AKPlayer and AKAudioPlayer print status is playing, but no sound is played. I think someone on stackoverflow asks this question, but no one gives a solution. . . Why does this happen?

**Comment by aure** [comment] 2019-04-15 08:29
Is this not a duplicate of https://github.com/AudioKit/AudioKit/issues/1733 ?

**Closed by aure** 2019-04-15 08:29 UTC
