### ISSUE TITLE
Clicking noise when defaultToSpeaker = true

### ISSUE THREAD

**Issue by Moriquendi** [AudioKit/AudioKit#2027] opened 2020-04-14 11:47 UTC
Hi folks,
I'm noticing "clicking noises" in recording output after updating library from `4.9.2` to `4.9.5`.
I've seen this has been mentioned in the past and apparently the issue is back (#1311 ).

I think this only happens when `defaultToSpeaker` is set to `true`.
**Code**: Sample code named "Recorder"

I'm testing that on iPhone 7 / iPhone XS.
No headphones plugged in.

**Comment by freezy7** [comment] 2020-04-18 03:35
Hello，#798 @sihwapark 's suggestion helped me, and when i didn't plug a headphone, i use the code below, it works for me. You can change it like this in the record demo and have a try. I think it is because need set the category and model of the audioSession before the `mic` init. If you use like this, you need self manager the audio session when the engine stop.

@aure hope dig the reason for it.

```swift
        // Session settings
        AKSettings.bufferLength = .medium
        AKSettings.defaultToSpeaker = false
        AKSettings.disableAVAudioSessionCategoryManagement = true
        AKSettings.disableAudioSessionDeactivationOnStop = true
        try? AVAudioSession.sharedInstance().setCategory(.playAndRecord)
        try? AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
      
//      do {
//          try AKSettings.setSession(category: .playAndRecord, with: .allowBluetoothA2DP)
//      } catch {
//          AKLog("Could not set session category.")
//      }
//
//      AKSettings.defaultToSpeaker = true
      

        mic = AKMicrophone()
```

**Comment by tcwalther** [comment] 2020-06-16 21:09
@aure I can reproduce this bug with both 4.9.5 and 4.10.1. Would you be happy reopening it?

**Comment by marcosgriselli** [comment] 2020-07-07 19:48
@tcwalther were you able to find a workaround for this? We're experiencing clicking noises on only a few specific models.

**Comment by aure** [comment] 2020-09-04 20:45
This is being addressed in the next version of AudioKit. It probably won't be fixed in 4.x

**Closed by aure** 2020-09-04 20:45 UTC
