### ISSUE TITLE
AKMIDISampler goes monophonic on iOS14

### ISSUE THREAD

**Issue by vrobi** [AudioKit/AudioKit#2271] opened 2020-09-18 21:05 UTC
I have an AKMIDISampler loading an .sf2 soundfont (piano) using loadMelodicSoundFont. This being triggered by AKAppleSequencer. On iOS 14 it plays a single note only! I rebuilt my app with Xcode 12/Audiokit 4.11 and it shows the same problem.  This is a major bug somewhere, totally consistent, happens every time. Any help for the workaround is appreciated!

UPDATE: after further tests I was able to demo the problem in a small test app modifying the SequencerDemo project. Apparently this is a problem in the sequencer itself, has nothing to do with the sound source, in the demo I have an AKFMOscillatorBank and the problem is there. I am posting the demo project, hopefully this helps. 

This project plays a single (dom 7) chord that is 2 beats long repeating every 8 beats
on iOS13 it plays correctly, on iOS14 the play is inconsistent, sometimes just a single note plays and the notelength is not correct either, a note is "stuck". Using XCode 12 and AK 4.11
[SequencerDemo.zip](https://github.com/AudioKit/AudioKit/files/5249131/SequencerDemo.zip)

**Comment by fvonk** [comment] 2020-09-20 16:14
Also have the same problem using .dls soundfont..

**Comment by Luftare** [comment] 2020-09-20 17:22
With xcode 12 and AudioKit v5-development branch:
- AppleSequencer often omits note start messages (midi number 144) of notes and appears to send stop messages (midi number 128) instead. This was tested by using a callback instrument.
- When multiple notes start simultaneously, tendency is that none is played. When slight randomization to note start time is applied, the notes are more likely to play
- Using varying channels per note within a single track does not seem to make any change

**Comment by aure** [comment] 2020-09-20 17:32
@Luftare Are you saying this is only happening with Xcode12 and v5-develop right? Just wondering if this is not a bug in Apple code that we should file a radar for or look at AudioKit.

**Comment by Luftare** [comment] 2020-09-20 18:04
Not necessarily exclusively with that setup. It's the only setup I've been able to get up-and-running. But looking at the git history it seems like Apple -side bug.

**Comment by fvonk** [comment] 2020-09-22 06:55
Hi!
I just checked apple example which successfully plays midi files with different soundfonts on iOS 14.
https://developer.apple.com/library/archive/samplecode/AVAEMixerSample

May be there is still bug in AudioKit framework version 4 on iOS 14 ?

**Comment by tieleman** [comment] 2020-09-22 08:35
I believe it is related to this: #2145 

The issue is that `AKMIDISampler` and `AKMIDICallbackInstrument` don't handle MIDI events correctly. They only process the first MIDI event and ignore the others. Apparently, Apple changed this internally for iOS 14 and now triggers this bug.

It was fixed (for `AKMIDISampler` only) in PR #2154, but only in the v5 branch. I think this fix (and one for `AKMIDICallbackInstrument` which suffers from the same issue) should be backported to v4 as well.

**Comment by Luftare** [comment] 2020-09-22 14:37
On `v5-develop`, switching from `MIDICallbackInstrument` (calling AppleSampler) to `MIDISampler` solved the issue for me.

**Comment by tieleman** [comment] 2020-09-22 15:19
@aure I've drafted a fix for the `v4-develop` branch that should take care of this, see #2281.

**Comment by aure** [comment] 2020-09-22 15:56
Merged (and applied to v5), thank you @tieleman

**Closed by aure** 2020-09-22 15:56 UTC

**Comment by megastep** [comment] 2020-09-22 22:39
I think this bug fix might justify a v4.11.2 release soon.

**Comment by megastep** [comment] 2020-09-23 10:47
v4.11.2 is now out with this fix.
