### ISSUE TITLE
INFO: Xcode11 - iOS 13 Simulators - Network MIDI driver error.

### ISSUE THREAD

**Issue by trevor-sonic** [AudioKit/AudioKit#1872] opened 2019-09-21 18:20 UTC
Hi,

I have **AudioKit 4.9** on **Xcode11** my working app is compiling but giving runtime error.
"Couldn't find MIDI network driver"

I checked on this issue and found the related [StackOverflow](https://stackoverflow.com/questions/57587784/couldnt-find-midi-network-driver-crash-in-ios-13-simulators) post that is pointing the problem as **iOS13 Simulators** problem. So it is not looking like related to AudioKit. 
But I'm also wondering; if there is something to do within the framework to prevent this crash? A condition for the compiler? Or someone figured out a solution already?

_(With this post I also wanted to warn the others about Xcode11 install, maybe it is better to wait for it. If this is unrelated please delete this issue)_

**Comment by aure** [comment] 2019-09-22 21:05
I worry about putting a band-aid to fix this in AudioKit because maybe it will just get fixed by Apple at some point and then we'd have to remember to take out the band-aid.

**Comment by trevor-sonic** [comment] 2019-09-24 12:04
Fortunately on iOS12.x Simulators there is no crash, so I stick to them for the moment and expecting a fix from Apple.🙏

**Comment by TheHiddenDuck** [comment] 2019-09-28 09:38
@aure could you please point out what that "band-aid" would be so I could try it locally for now?

**Comment by trevor-sonic** [comment] 2019-09-28 10:30
@TheHiddenDuck I tried on iOS 13 device. There is no issue (thankfully!) 
Only simulators are effected.

**Comment by TheHiddenDuck** [comment] 2019-09-28 10:31
@trevor-sonic thank you, that's very good news.

**Comment by aure** [comment] 2019-09-28 19:10
Since only simulators are affected you could be some kind of compilation condition in to check for that, but that sounds pretty hokey to me.  I'm going to close this issue for now.  Fingers crossed for Apple to fix this soon.

**Closed by aure** 2019-09-28 19:10 UTC

**Comment by emurray2** [comment] 2019-09-28 20:37
Hi Trevor,



I was getting the same error as you and this frusturated me. I searched for a solution for four days, and finally found one. I hope this will help you as well! Please follow these steps carefully:



1. Update Xcode to the latest version (if there is an update available)

2. Make sure your build target deployment version is set to iOS 13.0 (yours most likely is since you were using the iOS 13 simulator)

3. Quit the applications Simulator and Xcode if they are open

4. Open Finder

5. Navigate to the folder which your version of Xcode is located (mine is in my Applications folder)

6. Find Xcode

7. Hold down the control button on your keyboard and click on Xcode

8. A menu should pop up, select 'Show Package Contents'

9. You should see the folder called 'Contents' now open it

10. You should now see a variety of folders. Follow the directory path below to find the MIDI network drivers

11.  Navigate to /Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime

12. Repeat step 7 but this time, click on the file 'iOS.simruntime'

13. Open the 'Contents' folder inside of the 'iOS.simruntime'

15. Open the folder called 'MacOS'

16. You should see a document called 'iOS 13.0'

17. If you see this, congrats, you are in the right Simulator folder!

14. Exit out of the 'MacOS' folder back to the 'Contents' folder and Navigate to /Resources/RuntimeRoot/System/Library/Audio/MIDI Drivers

15. In this folder, you should see all of the MIDI network drivers which Xcode is missing.

16. If step 15 is true, exit out of the 'MIDI Drivers' folder back into the 'Audio' folder

17. Copy the whole 'MIDI Drivers' folder by selecting it and using (Command + C) or Edit -> Copy "MIDI Drivers", whichever you prefer

18. Exit out of the 'Audio' folder and navigate all the way back to the 'RuntimeRoot' folder

19. Navigate to /Library/Audio and you should see there is no folder called 'MIDI Drivers' here, only 'Plug-Ins' and 'Tunings'

20. You want to Paste the 'MIDI Drivers' folder you copied into this 'Audio' folder, use (Command + V) or Edit -> Paste Item

21. Now you should have two 'MIDI Drivers' folders: One in /System/Library/Audio and One in /Library/Audio

22. Close Finder and relaunch Xcode and try running your project again in the iOS 13 iPhone simulator



Now, Xcode should not complain about missing the MIDI Drivers, and your code should run without the EXE_BAD_ACCESS! I hope this helps, and please feel free to reach out to me if you have any more questions.



Best, 

Evan Murray

**Comment by aure** [comment] 2019-09-28 20:50
Well that a simple 25 step procedure! :)

**Comment by aure** [comment] 2019-09-29 03:37
Evan's method works. It's easier than it looks but it is 25 steps because it is very specific!

**Comment by sieren** [comment] 2019-10-01 12:45
I still feel like someone should file a radar with Apple, we might all file the same one and get it bumped up in the priority list.

**Comment by emurray2** [comment] 2019-10-01 13:30
Yes I agree. Now we also know what the problem is, so it should be easy for Apple to fix.

**Comment by trevor-sonic** [comment] 2019-10-03 15:47
Thanks a lot @emurray2 I give you 25 ⭐️ 👍

**Comment by emurray2** [comment] 2019-10-03 16:09
You're welcome! I'm glad this helped. @trevor-sonic

**Comment by trevor-sonic** [comment] 2019-10-07 11:11
@emurray2 I created a [blog post about this issue](http://lab.dejaworks.com/xcode11-ios13-simulators-couldnt-find-midi-network-driver-problem-solved/). I fully credit you in the post.

**Comment by emurray2** [comment] 2019-10-07 13:56
Awesome thank you for sharing!
