### ISSUE TITLE
Notes not stopping properly in MIDI sequencer

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/AudioKit#2454] opened 2021-04-12 05:23 UTC
Something strange has started happening with the `Sequencer`. I'm not sure exactly when, but recently.

The "stop playing notes" functionality has essentially stopped working. I have confirmed that my code is calling the stop method on each track, but the notes continue sustaining, which is a real problem in my app.

Here's what the code looks like that I execute in direct response to the user pressing the "stop" button:

```
    public func stop() {
        if let sequencer = sequencer {
            internalPlaybackState = .stopped
            sequencer.stop()
            for track in sequencer.tracks {
                track.stopPlayingNotes()
            }
            sequencer.rewind()
        }
    }
```

In that code, "sequencer" is just an AudioKit `Sequencer`. The "internalPlaybackState" is something related to my app that should have no bearing here.

I'd be happy to help you reproduce it. All the source code that I'm using for playback is in the SongSprout Swift Package located here:
https://github.com/dunesailer/SongSprout

The main playback class is `Orchestrion`.

**Comment by btfranklin** [comment] 2021-04-12 05:30
I looked into the history, and as I feared, about 2 months ago there were changes to this code:
https://github.com/AudioKit/AudioKit/commit/dc4dc349874fa2d19bbea6bab5cf30d5fb603c1d#diff-76f11ecd61519e497df84d95bafd58b4643651966912eb5e864849802f562e2b

I think somehow those changes broke this functionality, though I won't pretend to understand why.

**Comment by misterinterrupt** [comment] 2021-04-12 17:58
@btfranklin  should have the fix in a short bit

**Comment by aure** [comment] 2021-04-12 20:25
@misterinterrupt how long is a short bit? Once the PR is in, if you can test it @btfranklin I would like to get develop merged into main, so let me know if its all good.

**Comment by misterinterrupt** [comment] 2021-04-12 20:36
wrote that to mean: expect it within a few hours, and I am about to push the PR.

**Comment by misterinterrupt** [comment] 2021-04-12 21:43
https://github.com/AudioKit/AudioKit/pull/2456

@btfranklin 
before we merge, can you test your app using [this branch](https://github.com/misterinterrupt/AudioKit/tree/%232554-sequencer-stop-notes-on-stop) (from my fork) ?

**Comment by aure** [comment] 2021-04-12 21:58
I went ahead and merged to develop so @btfranklin doesn't have to do anything fancy to test.

**Comment by btfranklin** [comment] 2021-04-12 22:22
Yes, I am happy to confirm that this is now fixed. Fantastic! Thanks for the super-fast turnaround on this, @misterinterrupt and @aure !

**Comment by btfranklin** [comment] 2021-04-13 06:44
Okay, I have some bad news. While this update did reduce the frequency of this bug, it did not eliminate it after all. As I've been continuing to develop my app tonight with the latest changes, I'm still easily able to create conditions where notes that have been started will continue to sustain indefinitely if you invoke the stop function I mentioned in my original report. I don't think this can be considered fixed yet. Sorry :(

**Comment by misterinterrupt** [comment] 2021-04-13 06:49
@btfranklin  can you describe your use cases here?

**Comment by misterinterrupt** [comment] 2021-04-13 06:55
side note i called to mention
i dont think you need this code:
`for track in sequencer.tracks {
         track.stopPlayingNotes()
  }`

**Comment by btfranklin** [comment] 2021-04-13 07:12
Yeah, I was just being hyper-thorough. Basically just doing everything that seemed like it might stop things, since it doesn't happen frequently (i.e. it's user-invoked only) and therefore I could afford to be a little wasteful with doing extra stuff. This was also originally written against AudioKit 4 and updated later to be AK5 compatible, so some stuff I wasn't really clear on whether it was still needed or not.

As far as use cases go, the app presents a bunch of different style configurations. The user picks one, at which point a unique MIDI sequence is generated from that style. Then they can click "play" and it starts playing. When they press "stop", it stops. If they pick a different style, the whole sequencer gets torn down and rebuilt.

This is all done from this class: https://github.com/dunesailer/SongSprout/blob/main/Sources/SongSprout/Orchestrion.swift

I call "prepare" when they select a new style, then the "play" and "stop" methods when they interact with those.

**Comment by btfranklin** [comment] 2021-04-13 07:16
I just now updated my code to remove the superfluous loop you identified. I think that's a good change, but I can still reproduce this problem. For what it's worth, it seems to be really showing up when I'm using instruments that have potentially infinite sustain, like pads and stuff. I'm not sure how the code is identifying currently playing notes and sending note-off to them, but maybe that's missing some of them somehow. That's what it's acting like, anyway.

**Comment by misterinterrupt** [comment] 2021-04-13 07:23
I would have done similar to try and make things work if they weren't

Earlier, I pulled your repo but there was no xcode project, so I couldn't move forward with debugging it directly.

each track has its own c++ audiounit dsp function or 'engine' in the code..
inside there, every time a note on is sent, a bit in a set of 128 bits is set to 1.
when a note off is sent, the bit is set back to 0

**Comment by misterinterrupt** [comment] 2021-04-13 07:28
are you starting and stopping when you reproduce the issue? 
is it the removal of tracks/ sets of tracks that makes it happen?

**Comment by misterinterrupt** [comment] 2021-04-13 07:31
if it is happening when you are destroying the sequencer tracks, perhaps I need to send note offs in the deconstructor ....

**Comment by btfranklin** [comment] 2021-04-13 07:31
Yeah, SongSprout itself is an open source Swift package, but the app that uses it is not open source. That's why there's no Xcode project in the repo.

I am indeed starting and then stopping to reproduce the issue. I can select the same style and click start/stop/start/stop a bunch of times and sometimes the problem will happen, other times it will not.

Once it has happened, I can do another start/stop cycle (without changing anything else) and it is able to "pick up" the lingering note and kill it on future playbacks. So it's not like a zombie note or something.

**Comment by misterinterrupt** [comment] 2021-04-13 07:36
yuck, horrible!

**Comment by btfranklin** [comment] 2021-04-13 07:37
I can get it to happen just within these two blocks of code, with nothing else getting invoked:

```
public func play() {
        guard let song = self.song else {
            internalPlaybackState = .initialized
            return
        }

        if playbackState == .initialized {
            song.populateTracks()
        }

        sequencer?.tempo = tempo
        sequencer?.playFromStart()
        internalPlaybackState = .playing
    }

    public func stop() {
        if let sequencer = sequencer {
            internalPlaybackState = .stopped
            sequencer.stop()
            sequencer.rewind()
        }
    }
```

So really the only things getting called on the sequencer are tempo, playFromStart(), stop(), and rewind().

**Comment by misterinterrupt** [comment] 2021-04-13 07:39
ok, thanks!
I have a test app  that is similar, switching between various sequences, starting stopping, looping/not  etc
 I tried to jam the sequencer guts as well.. only had one track running at a time
Now I'll add some more tracks, also add setting of tempo and see what I can find

**Comment by btfranklin** [comment] 2021-04-13 07:47
I'm going to have to turn in for the evening, but I can play more with this tomorrow if you haven't found anything by then.

I have to say that it seems really interesting that it can "pick up" lingering notes from previous playbacks and kill them later. That really makes me think that it's either 
1) missing notes the first time (don't know how) ...or... 
2) the notes are somehow not processing the "note off" that they're sent sometimes.

This could be happening to *any* note, but it's only obvious on the ones with infinite looping sustain, since the others fade out even though they might still actually be playing.

**Comment by misterinterrupt** [comment] 2021-04-13 08:52
Thanks for all of your feedback here.

The need for tracking currently playing notes is a side effect of midi protocol scheduling and sustaining note interruptions that happen often e.g. seeking to a position (my next fix), stopping playback(last fix), removing notes, editing start and end times of notes, etc. 

These things happen while the sequencer core is pushing out the on and off MIDI messages. The sequencer needs to be able to check if sustained notes still have valid endings in the sequence data. Depending on what has changed, they may need to be ended.

you prolly wont need to look for more in your code for now. I definitely see things to fix, looking beyond just the note tracking on stop. Some small some bigger, I will track the fixes here.

**Comment by btfranklin** [comment] 2021-04-14 06:40
Hey guys (esp. @misterinterrupt), to make your life easier, and to make it simple for you to reproduce this bug, I added a playground to SongSprout which interacts with the Orchestrion close enough to the way that the full app does it that I'm able to reproduce the problem in just the simple playground. Maybe this will help with debugging.

https://github.com/dunesailer/SongSprout/tree/main/Sources/Playgrounds/Orchestrion%20Playground.playground

I've been able to reproduce the bug multiple times in my Xcode using that playground. I hope you will have similar luck.

**Comment by btfranklin** [comment] 2021-04-14 06:50
Just to be 100% clear: If you clone the SongSprout repo, you should be able to open the whole thing in Xcode as a Swift Package, and then you can run the Playground from inside there.

**Comment by misterinterrupt** [comment] 2021-04-14 06:52
alrighty, thanks for the efforts
I was also able to recreate the bug, so I spent some time today fixing edge cases, still more work to do though

**Comment by misterinterrupt** [comment] 2021-04-14 09:45
@btfranklin SongSrpout is super fun :D   
I believe I have fixed the stuck notes. I need to do some more testing tomorrow, hope to have something for you to test then.

**Comment by btfranklin** [comment] 2021-04-15 03:40
@misterinterrupt Haha Thank you! It's the result of years of R&D. I'm actually really glad to have a playground for it now, too. This was good motivation.

**Comment by btfranklin** [comment] 2021-04-20 00:12
Any update on this?

**Comment by misterinterrupt** [comment] 2021-04-20 07:48
Yes, I believe I've got your case covered. it was very helpful to have your playground in order to trap this round of stuck note issues.

Working on expanding the engine test coverage for the PR now.

Some new code happened in the v5 development branch and I made a small change to your sequencer usage, so I will also push a PR to your playground.

I took the opportunity to break down and categorize the sequencing test cases that this issue is a part of. 

Some of the unrelated cases will become their own new issue. 

All of it will end up in some nice new documentation and be part of making the sequencer much more robust.

**Comment by btfranklin** [comment] 2021-04-20 15:55
Sweet. I'm pretty excited to see it (obvi).

**Comment by misterinterrupt** [comment] 2021-05-03 03:07
@btfranklin apologies for the wait. I was interrupted (moved to a new place), so my refactor stuff wont go in before the v5 release date.

I had discussed this issue with @eljeff and came up with the least code likely needed. I am hoping this will solve your case. 
(also, I think your play button ought to call the sequencer.stopAllNotes() method in case it is already playing)

https://github.com/AudioKit/AudioKit/pull/2480

**Closed** 2021-05-03 06:19 UTC

**Comment by btfranklin** [comment] 2021-05-11 17:33
I know this is already closed, but just for the record: I have confirmed that this does fix the problem in my product. THANK YOU!

**Comment by aure** [comment] 2021-05-11 22:19
@btfranklin Thanks for the followup, feels good to know we addressed your problem.

**Comment by sridharrajagopal** [comment] 2023-06-13 01:17
I wonder if I'm hitting the same issue. I'm using a Flute or Clarinet from STKAudioKit through a sequencer, and find that the instrument does not stop. 

I also see the following output in the console:

`Flute::stopBlowing: argument is less than or equal to zero!`


I've not investigated yet if that may be related. 

I've included my code below

Thanks, 
Sridhar


```
struct FluteMetronomeData {
    var isPlaying = false
    var tempo: BPM = 120
    var timeSignatureTop: Int = 4
    var beatNoteVelocity = 100.0
    var currentBeat = 0
}

class FluteConductor: ObservableObject, HasAudioEngine {
    let engine = AudioEngine()
    let flute = Flute()
    let reverb: Reverb
    let mixer = Mixer()
    var sequencer = Sequencer()
    
    let scale = [0, 2, 4, 5, 7, 9, 11, 12]

    let playRate = 3.0


    @Published var data = FluteMetronomeData() {
        didSet {
            data.isPlaying ? sequencer.playFromStart() : sequencer.stop(); sequencer.rewind(); flute.stop()

            sequencer.tempo = data.tempo
            // updateSequences()
        }
    }
    
    func updateSequences() {
        let octave = 60

        var track = sequencer.tracks.first!

        track.length = Double(scale.count*2)

        track.clear()
        
        let vel = MIDIVelocity(Int(data.beatNoteVelocity))
        var beat = 0
        var duration = 1.0
        for note in scale {
            track.sequence.add(noteNumber: MIDINoteNumber(note + octave), velocity: vel, position: Double(beat), duration: duration)
            beat += 1
            // duration = duration + 0.1
        }
        
        for note in scale.reversed() {
            track.sequence.add(noteNumber: MIDINoteNumber(note + octave), velocity: vel, position: Double(beat), duration: duration)
            beat += 1
            // duration = duration + 0.1
        }

//        track = sequencer.tracks[1]
//        track.length = Double(data.timeSignatureTop)
//        track.clear()
//        for beat in 0 ..< data.timeSignatureTop {
//            track.sequence.add(noteNumber: MIDINoteNumber(beat), position: Double(beat), duration: 0.1)
//        }
    }

    init() {
        let fader = Fader(flute)
        fader.gain = 5.0
        
        reverb = Reverb(fader)
        
        _ = sequencer.addTrack(for: flute)
        
//        callbackInst = CallbackInstrument(midiCallback: { _, beat, _ in
//            self.data.currentBeat = Int(beat)
//            print(beat)
//        })
//
//        _ = sequencer.addTrack(for: callbackInst)
        
        updateSequences()

        mixer.addInput(flute)
        // mixer.addInput(callbackInst)


        engine.output = mixer
    }
}
```

**Comment by sridharrajagopal** [comment] 2023-06-13 01:24
I think the error message is related to the Flute/Clarinet not stopping. keyOff() is not getting called when rate <= 0.0 

Flute::stopBlowing: argument is less than or equal to zero!

```
void Flute::stopBlowing(StkFloat rate) {
  if (rate <= 0.0) {
    oStream_ << "Flute::stopBlowing: argument is less than or equal to zero!";
    handleError(StkError::WARNING);
    return;
  }

  adsr_.setReleaseRate(rate);
  adsr_.keyOff();
}
```

**Comment by sridharrajagopal** [comment] 2023-06-13 01:32
I've confirmed that the rate is zero. It comes from 

```
void STKInstrumentDSP::handleMIDIEvent(AUMIDIEvent const& midiEvent) {
    isStarted = true;
    uint8_t status = midiEvent.data[0] & 0xF0;

    uint8_t veloc = midiEvent.data[2];
    auto note = midiEvent.data[1];
    auto amplitude = (AUValue)veloc / 127.0;
    float frequency = pow(2.0, (note - 69.0) / 12.0) * 440.0;

    if(auto instr = getInstrument()) {

        switch(status) {
            case MIDI_NOTE_OFF : {
                if (note > 127) break;
                instr->noteOff(amplitude);
                break;
            }
            case MIDI_NOTE_ON : {
                if (note > 127 || veloc > 127) break;
                instr->noteOn(frequency, amplitude);
                break;
            }
        }
    }
}
```

where amplitude is zero . 

Looking at the stopBlowing code, I would think it would be good to call adsr_.keyOff() even if rate = 0.0 (maybe even <= 0.0)

Thanks,
Sridhar
PS - This issue looks like it may belong to STKAudioKit?
