### ISSUE TITLE
Xcode - iOS Csound error - Sound not working in iPhone Simulator?

### ISSUE THREAD

**Issue by NehalRaj** [audiokit/AudioKit#247] opened 2015-10-26 05:34 UTC
0dBFS level = 32768.0

Csound version 6.05 (float samples) Sep 18 2015

libsndfile-1.0.26pre6

    2015-10-25 22:30:02.544 TestPrg1[29291:738144] 1 MIDI sources

2015-10-25 22:30:02.546 TestPrg1[29291:738144] MIDI source 0: Session 1

0dBFS level = 32768.0

Csound version 6.05 (float samples) Sep 18 2015

libsndfile-1.0.26pre6

 2015-10-25 22:30:03.614 TestPrg1[29291:738168] 1 MIDI sources

2015-10-25 22:30:03.614 TestPrg1[29291:738168] MIDI source 0: Session 1

2015-10-25 22:30:04.574 TestPrg1[29291:738168] ***Failed to disable audio input.

2015-10-25 22:30:04.575 TestPrg1[29291:738168] ***Failed to enable audio output.

2015-10-25 22:30:04.620 TestPrg1[29291:738170] Csound Error: INIT ERROR in instr 1: 

2015-10-25 22:30:04.620 TestPrg1[29291:738170] Csound Error: Invalid ftable no. 2000.000000

2015-10-25 22:30:04.620 TestPrg1[29291:738170] Csound Error: 

2015-10-25 22:30:04.621 TestPrg1[29291:738170] Csound Error:  - note deleted.  i1 had 1 init errors

2015-10-25 22:30:04.621 TestPrg1[29291:738170] Csound Error: 

Csound tidy up: Terminated

(lldb)

**Comment by aguycalledalex** [comment] 2015-10-30 18:49
i am also not getting any sound out from the simulator... using swift here

**Comment by aure** [comment] 2015-10-31 00:59
Audio is not able to be used on your system for some reason:
"***Failed to enable audio output."

There is very little information to investigate in this issue, so I am closing it for now.

**Closed by aure** 2015-10-31 00:59 UTC

**Comment by Yanakyl** [comment] 2015-11-09 18:30
I've had the same problem after setting up the project looking at the first videos.
The problem is just with the simulator, putting a small delay solves the error.
With
<code>
        NSThread.sleepForTimeInterval(1)
</code>
before
<code>
        instrument.play()
</code>
It works in the simulator too.

**Comment by narner** [comment] 2015-11-09 18:35
@Yanakyl That's good to know...definitely sounds like more of a bug with the simulator than with anything else.

**Comment by aure** [comment] 2015-11-09 18:38
Well, I think its a common enough problem that I'll add a plist entry for it.  Instead of implement a NSThread sleep like this, can you see if changing the runOrchestra method works as well?  Basically change cycles > 100 to cycles > 200 to add another second.  You can experiment to minimize the cycles.

**Comment by Yanakyl** [comment] 2015-11-09 20:20
@aure I'm sorry but I don't find any runOrchestra method, it's all new to me. 
Anyway in a real scenario playing a note is not the first thing you do when the program is loading up. The sleep was just to check the idea of the simulator not having time to load everything.

**Comment by aure** [comment] 2015-11-09 20:47
In any event, the latest code in the development branch allows a wait time to be set in AudioKit.plist.

**Comment by Yanakyl** [comment] 2015-11-09 21:04
Ok I've seen it, I'm using the master branch now. I'll give it a try later on then.
