### ISSUE TITLE
Crash in AKMidi() openMIDIIn()

### ISSUE THREAD

**Issue by ClayApps** [audiokit/AudioKit#304] opened 2016-02-23 20:18 UTC
Using your midiMonitor project:

MIDI Enabled
created client
Opening MIDI In
SourceCount: 3
MIDI Inputs:
midiIn at Session 1
midiIn at Gorges Midi Keyboard #1
midiIn at Gorges Midi Keyboard #2
MIDI Destinations:
Destination at Session 1
Destination at Gorges Midi Monitor
Opening MIDI In
SourceCount: 3
fatal error: Array index out of range

 I updated the viewDidLoad() thusly:

```swift
override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        midi.openMIDIIn("Session 1z")
        midi.addListener(self)
        
        midi.printMIDIInputs()
        midi.printMIDIDestinations()
        
        midi.openMIDIIn("Gorges Midi Keyboard #1")
        midi.openMIDIOut("AK.Midi.out")
    }   
```
Specifically here:

```swift
public func openMIDIIn(namedInput: String = "") {
        print("Opening MIDI In")
        var result = OSStatus(noErr)
        
        let sourceCount = MIDIGetNumberOfSources()
        print("SourceCount: \(sourceCount)")
        for var i = 0; i < sourceCount; ++i {
            let src = MIDIGetSource(i)
            var inputName: Unmanaged<CFString>?
            inputName = nil
            MIDIObjectGetStringProperty(src, kMIDIPropertyName, &inputName)
            let inputNameStr = (inputName?.takeRetainedValue())! as String
            if namedInput.isEmpty || namedInput == inputNameStr {
                midiInPorts.append(MIDIPortRef())
                result = MIDIInputPortCreateWithBlock(
                    midiClient,
                    midiInName,
                    &midiInPorts[i],
                    MyMIDIReadBlock)
                if result == OSStatus(noErr) {
                    print("created midiInPort at \(inputNameStr)")
                } else {
                    print("error creating midiInPort : \(result)")
                }
                MIDIPortConnectSource(midiInPorts[i], src, nil)
            }
        }
    } 
```

This line:

```swift
                   &midiInPorts[i],
```

Note that the line its crashing on in the VC:
```swift
midi.openMIDIIn("Gorges Midi Keyboard #1")
```

Is for a midi input device that actually exists on the device, while:

```swift
midi.openMIDIIn("Session 1z")
```
Does not exist!

**Comment by aure** [comment] 2016-02-26 21:28
Hi,  this is going to be hard to debug because it is specific to your system, but I can try to replicate a similar situation over here.

**Comment by ClayApps** [comment] 2016-02-26 21:52
Nah it's easy. Just run an App that creates a virtual source / destination then add those few lines to your demo with the names adjusted as necessary and your'e done.

**Comment by rmann22** [comment] 2016-03-29 13:28
I'm getting the same crash. Is there an update to this?

**Comment by aure** [comment] 2016-04-29 20:34
I'm not able to reproduce this.  Can someone provide exact steps to making this happen on any system?

**Comment by aure** [comment] 2016-04-30 19:32
Actually I finally see this error so I think I should be able to fix it.

**Comment by aure** [comment] 2016-04-30 19:58
Should be fixed on the develop branch:

https://github.com/audiokit/AudioKit/commit/7d00ba80c31b916e096d8097f7e7ca5026f719e9

**Closed by aure** 2016-04-30 19:58 UTC
Labels: question
