### ISSUE TITLE
Unable to play sound with AKOperation.metronome

### ISSUE THREAD

**Issue by fever324** [audiokit/AudioKit#584] opened 2016-10-23 02:18 UTC
Hi,

I was trying to create a simple metronome iOS app using swift 3.0. However I was unable to hear any sound after the application starts. Could you please take a look at it and let me know know what I could have done wrong?  Thank you!

In the console, it printed the following. I'm not sure if that is related here.

Could not find function called '@\204b'.
@\204b returned an error.

Here is my code of the view controller. 

```swift
import UIKit
import AudioKit

class ViewController: UIViewController {

    var currentFrequency = 60.0
    let generator = AKOperationGenerator() { parameters in
        let beep = AKOperation.sineWave(frequency: 480)
        
        let metronome = AKOperation.metronome(frequency: parameters[0] / 60)
        
        let beeps = beep.triggeredWithEnvelope(
            trigger: metronome,
            attack: 0.01, hold: 0, release: 0.05)
        return beeps
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

    }
    
    override func viewDidAppear(_ animated: Bool) {
        generator.parameters = [currentFrequency]
        
        AudioKit.output = generator
        AudioKit.start()
        generator.start()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

```

**Comment by aure** [comment] 2016-10-23 04:41
I just wanted to confirm that I am getting the same error as you are when I run this code.  And I do think the code is fine.  It runs in playgrounds but not on the simulator which is very bizarre.  Clearly an issue, ie. my fault.

**Comment by fever324** [comment] 2016-10-23 05:16
Thank you for getting back to me. Please let me know if there is any way that I can help figuring this out!  🙂

**Comment by junhohong** [comment] 2016-10-23 05:53
Try instantiating the generator inside viewDidLoad or viewDidAppear. This may temporarily fix the issue.

**Comment by junhohong** [comment] 2016-10-23 05:57
@aure That's the same error I got with the headphone jack issue. I think it happens when AudioKit.start() is called before the output has been properly built. My guess is that when the generator is built in the scope of the class, that may be happening before AudioKit is properly set up?

**Comment by aure** [comment] 2016-10-23 06:35
Thanks for the insight Jun Ho, but I think this particular case has to do operation initialization order, and its on me. :-/

**Comment by fever324** [comment] 2016-10-23 21:22
@junhohong Thanks for the help! I've moved the code inside viewDidApear and it works now!

**Comment by aure** [comment] 2016-10-23 22:35
@junhohong Wow, here I was chasing all these other issues and I didn't even try that.  Glad it works now!  I will close this issue.

**Closed by aure** 2016-10-23 22:35 UTC

**Comment by junhohong** [comment] 2016-10-24 10:08
@aure Improper order of initializations when working with generators does seem to be the root cause of crashing when AudioKit attempts to restart though. Rebuilding the output from scratch at every restart could maybe be avoided if we figure this out. Might be worth looking into.
