### ISSUE TITLE
Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10865'

### ISSUE THREAD

**Issue by lmick002** [audiokit/AudioKit#605] opened 2016-11-06 22:46 UTC
First. Thanks for the awesome library. 
Ive been trying to test out the recording Demo, but I keep receiving this exception : 

2016-11-06 17:42:28.868975 RecorderDemo[7971:2099915] [central] 54:   ERROR:    [0x1b28eec40] >avae> AVAudioNode.mm:751: AUSetFormat: error -10865
2016-11-06 17:42:28.870141 RecorderDemo[7971:2099915] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10865'

any help would be appreciated.Thanks

**Comment by aure** [comment] 2016-11-07 06:04
Hi, I just tested this on my machine, on the simulator and it works fine.  Can you give me more information about where you're trying to run it and what version of Xcode you have and what version of AudioKit.  etc.

**Comment by lmick002** [comment] 2016-11-07 06:16
Sure Xcode 8.1 (Version 8.1 (8B62)) and AudioKit 3.4.3. Ive been trying to run it on a iPhone 5 and a iPhone 6. The example project loads successfully but once I tapped the button to switch the state to .recording  it throws the error -> 

AKNodeRecorder: recording
2016-11-07 01:16:33.962321 RecorderDemo[8327:2210490] [central] 54:   ERROR:    [0x1b28eec40] >avae> AVAudioNode.mm:751: AUSetFormat: error -10865
2016-11-07 01:16:33.970065 RecorderDemo[8327:2210490] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10865'
*** First throw call stack:
(0x18da841c0 0x18c4bc55c 0x18da84094 0x1a709f78c 0x1a7115518 0x1a711544c 0x1a7114e48 0x1a7112a8c 0x1002deb6c 0x100073a88 0x100074868 0x1939027b0 0x193902730 0x1938ecbe4 0x19390201c 0x193901b44 0x1938fcd8c 0x1938cd858 0x1940bacb8 0x1940b4720 0x18da32278 0x18da31bc0 0x18da2f7c0 0x18d95e048 0x18f3e1198 0x193938628 0x193933360 0x100070d00 0x18c9405b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by aure** [comment] 2016-11-07 06:20
Does it work for you using the simulator but not the actual device?

**Comment by aure** [comment] 2016-11-07 06:22
That's what I am getting.

**Comment by lmick002** [comment] 2016-11-07 06:25
Let me check the simulator

**Comment by lmick002** [comment] 2016-11-07 06:28
Yeah it works fine in the simulator

**Comment by aure** [comment] 2016-11-07 06:44
This was working recently, so its something new, thanks for finding it.

**Comment by lmick002** [comment] 2016-11-07 06:49
Yes it was. I was trying to figure out what specifically changed(other than the file naming, etc) between last commits that is causing it to throw the error, but to no avail.

**Comment by aure** [comment] 2016-11-07 07:17
Checking all the examples out on the phone and there are a few issues that might be related.  Working on it...

**Comment by lmick002** [comment] 2016-11-07 07:30
okay thx

**Comment by samuelbeek** [comment] 2016-11-08 14:57
Let me know if I can help @aure

**Comment by aure** [comment] 2016-11-09 19:10
@samuelbeek If you want to help, please do.

**Comment by aure** [comment] 2016-11-10 19:17
This seems to be due to recorder installing the tap on a node and not getting the format set properly.  I'm not sure why this has stopped working because my code seems to be about the same.  I've even reverted some code with no luck.  I'll keep pushing on it but I thought you deserved an update at least.

**Comment by aure** [comment] 2016-11-10 19:57
More info: The processing format that comes from AVAudioFile appears to be reported incorrectly on the phone, but not on the simulator.

**Comment by lmick002** [comment] 2016-11-10 20:33
thanks @aure for the update.

**Comment by lmick002** [comment] 2016-11-10 20:34
looks like we're getting warmer!

**Comment by aure** [comment] 2016-11-12 07:36
So, here's what happened (I had posted all of this into the wrong issue).

a) I tried out the recorder on my iPad pro and it worked fine
b) It works on my phone too, if I disconnect the lightning cable after installing the app and rerun it.

I had theorized that it was because I have an iPhone 7 which has no headphone jack and I thought maybe the lightning cable was taking over my audio.  But, you have an iPhone 5 and 6, so I am not sure that is truly the cause.

Can you try this technique on your devices and see if it solves the problems?

**Comment by lmick002** [comment] 2016-11-12 15:08
Yeah Ive tried that method as well. and Im still getting the same node error. I tried installing and running without the lightning cable attached as well as a fresh install and running without the lightning cable

**Comment by aure** [comment] 2016-11-12 20:41
Well, I have tested on all my devices and it works, so I have to ask the other basic questions.  Which branch are you using?  If you're already using develop, have you pulled the most recent changes? Have you rebuilt the framework using build_frameworks.sh in the Frameworks directory?  Thanks.

**Comment by lmick002** [comment] 2016-11-13 20:47
okay ill test from my end and update you.  I'm using 3.4.3. and I'm running the framework from a pod install

**Comment by aure** [comment] 2016-11-13 20:53
It could be that recent changes fixed it.  You could just try grabbing the develop branch version of the recorder demo.

**Comment by lmick002** [comment] 2016-11-13 20:58
will do @aure I'll update you.

**Comment by aure** [comment] 2016-11-13 21:02
Just because this isn't an actionable issue for me, I'm going to close it, but feel free to reopen it with more information or updates.

**Closed by aure** 2016-11-13 21:02 UTC

**Comment by lmick002** [comment] 2016-11-13 21:49
its been resolved in the development branch thanks 1

**Comment by aure** [comment] 2016-11-13 23:38
Yay!

**Comment by DebanjanChakrabortyCN** [comment] 2017-07-14 14:26
I'm facing the same issue here. It works perfectly in simulator but crashes in iPhone. I'm using the latest code that is present in the git.

**Comment by aure** [comment] 2017-07-16 05:11
@DebanjanChakrabortyCN I just tested it on my iPhone and it works.  In general its bad Github etiquette to follow up very old closed issues, so I am disabling adding comments to this issue.
