### ISSUE TITLE
Crash in MultiSegmentEnvelopeGenerator:advanceToSegment(int)

### ISSUE THREAD

**Issue by CrossProd** [AudioKit/AudioKit#1667] opened 2019-02-05 07:28 UTC
Since AudioKit version 4.5.3 we have a crash occurring when playing samples with AKSampler.

We are unable to reproduce it but through fabric crashlytics we can see about 2.5 % of the sessions are affected.

We made sure the order of initializing audiokit, creating the aksampler etc is in the right order.

I have included a crashlog. Please let me know if more info is needed :)

[crashlog.txt](https://github.com/AudioKit/AudioKit/files/2831162/crashlog.txt)

**Comment by getdunne** [comment] 2019-02-05 13:44
There have been changes to this section of the code since 4.5.3. Can you test with a more recent build? Which version are you using now?
As far as I can tell, the crash occurs when you have AKSampler set to mono mode, but with legato off. You may want to concentrate your testing on that case.

**Comment by CrossProd** [comment] 2019-02-05 14:01
We have tested it with 4.5.5 and 4.5.6 (recently updated to this version hoping it would fix this crash.)

The AKSampler is used with its default settings except:

- releaseDuration is set to values between 0.5 and 5 seconds
- masterVolume is set to values between 0.5 and 1.0

We do not set any other properties on AKSampler.

We load samples using loadSFZ()and play samples using the play() and release() method. We only interact with AudioKit on the main thread.

The complete audio chain is very basic:

AudioKit.output is set to an instance of AKMixer initialised with the AKSampler singleton. After that AudioKit.start is called. 

Maybe the issue occurs when going to background/foreground. We call AudioKit.stop when the app has entered background status. When the app comes back to the foreground we call AudioKit.start. We also recall loadSFZ after coming back to the foreground, because otherwise no sound would be played interacting with the sampler.

**Comment by getdunne** [comment] 2019-02-05 14:09
Stop/start seems like a possible cause. I will try doing some tests with AKSampler and start/stop.

**Comment by getdunne** [comment] 2019-02-05 15:50
I have tested starting and stopping AudioKit using AKSampler on the Mac, and I can't reproduce this yet.
You mentioned "We load samples using loadSFZ()and play samples using the play() and release() method.". AKSampler has no release() method, only stop(). Was this a typo?

**Comment by CrossProd** [comment] 2019-02-06 07:40
My bad, I indeed meant stop() instead of release().

And apologies for not mentioning this previously but this crash occurs in an iOS app.

**Comment by CrossProd** [comment] 2019-02-21 08:42
This is still happening in production with version 4.6.1.

**Comment by aure** [comment] 2019-03-25 22:14
We weren't able to determine enough from the crashlog file to really know what to look for.  Is there any way you can create an example project that demonstrates the crash?  Until we can get more information, I'll close the issue, but feel free to re-open it as necessary.

**Closed by aure** 2019-03-25 22:14 UTC
