### ISSUE TITLE
EXC_BAD_ACCESS crash when opening audio from NSURL in AKAudioFile for reading

### ISSUE THREAD

**Issue by seyhunak** [audiokit/AudioKit#691] opened 2017-01-15 21:45 UTC
Hello,

If I try to read file from URL, in Amazon Polly
Output format: mp3 (also tested with pcm)

I'm getting EXC_BAD_ACCESS

`let audioFile = try AKAudioFile(forReading: url as URL)
`

But if I go with AVPlayer

```
self.audioPlayer.replaceCurrentItem(with: AVPlayerItem(url: url as URL))
self.audioPlayer.play()
```
It works.

Anyone face this problem?

Using: Swift 3, AudioKit (3.5)

Thanks.

**Comment by aure** [comment] 2017-01-16 05:58
Seems related to: https://github.com/audiokit/AudioKit/issues/639

**Comment by seyhunak** [comment] 2017-01-16 08:39
@aure Thanks, I did checked issue #639 but looks like file must be download at first in order to open forReading with AKAudioFile (AVAudioFile)

If I download audio file from network at first it working and also file is not corrupted. 
So, I was trying to do without download, trying streaming actually.

**Comment by aure** [comment] 2017-01-16 08:43
Hmm, I didn't really notice that you're using AVPlayer vs. AVAudioPlayer.  From what I can tell about AVPlayer is that its a high level do-it-all player that doesn't hook into the AVAudioEngine like AVAudioPlayer.  Am I wrong about this?  If so, we can't really use it in AudioKit.

**Comment by aure** [comment] 2017-01-21 05:54
If you want to reopen this issue that's fine, but otherwise I'll say the corrupt file issue is a duplicate of issue 639 and AVPlayer can stream, but AudioKit cannot, currently  anyway.

**Closed by aure** 2017-01-21 05:54 UTC
