### ISSUE TITLE
AKMIDISampler crash in xCode12 + ios14

### ISSUE THREAD

**Issue by brizzly** [AudioKit/AudioKit#2276] opened 2020-09-21 09:20 UTC
My app crash when I build AudioKit iOS 4.11.1 on AKMIDISampler.

Error log 
Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKMIDISampler'

**Comment by impmaarten** [comment] 2020-09-21 10:41
Same issue occurs for `AudioKit.AKSampler`

**Comment by ryangenz** [comment] 2020-09-21 12:03
This is probably a duplicate of this issue:
https://github.com/AudioKit/AudioKit/issues/2272
The above thread has a workaround.

- [ ] 
Duplicate of 2272#

**Comment by ryangenz** [comment] 2020-09-21 12:04
Duplicate of #2272

**Comment by impmaarten** [comment] 2020-09-21 14:09
> Duplicate of #2272

The suggested is not really a proper solution. It's showing and trying to use the initialisers of the classes that do not exist, causing initialisers with optional parameters (that have default values) to conflict now. I had to define the "default" parameter to make it recognise the correct initialisers, which is not very pretty as shown below, otherwise `Fatal error: Use of unimplemented initializer 'init()' for` is thrown.

`AKSampler()` -> `AKSampler(masterVolume: 1.0)` 
`AKMIDICallbackInstrument()` -> `AKMIDICallbackInstrument(midiInputName: "AudioKit Callback Instrument")`

**Comment by aure** [comment] 2020-09-22 16:25
Its not pretty but its going to have to be good enough for now since we'll be onto v5 for the next release.

**Closed by aure** 2020-09-22 16:25 UTC

**Comment by ingconti** [comment] 2020-11-05 07:53
my two cents for "sampler demo"


class Conductor {
    private var sequencer: AKAppleSequencer!
    private var mixer = AKMixer()
    private var arpeggioSynthesizer = AKMIDISampler(**midiOutputName: nil**)
    private var padSynthesizer = AKMIDISampler(**midiOutputName: nil**)
    private var bassSynthesizer = AKMIDISampler(**midiOutputName: nil**)
    private var drumKit = AKMIDISampler(**midiOutputName: nil**)
    private var filter: AKMoogLadder?
....

**Comment by RichardBoyder** [comment] 2020-11-10 11:40
How do i perform the fix for this:
`Use of unimplemented initializer 'init()' for class 'AudioKit.AKAudioFile'`
