### ISSUE TITLE
receivedMIDINoteOn of MIDIListener protocol is not sent

### ISSUE THREAD

**Issue by gilhadas** [AudioKit/AudioKit#2295] opened 2020-10-08 15:19 UTC
in branch v5-master, after Merge branch 'v5-develop' into v5-master commit 41dbdf45101b4f345a393b8ca4233b86323aeb4f

It worked before, but now  it stoped working
I receive receivedMIDINotification only

**Comment by aure** [comment] 2020-10-08 16:03
@yuriizubkov Did you test receiving MIDI?

**Comment by yuriizubkov** [comment] 2020-10-08 16:37
@aure yes, I am using CC, program change, note on/off and SysEx messages in my app. 
@gilhadas what OS you are using?

**Comment by gilhadas** [comment] 2020-10-08 16:59
I'm using iOS 14.0.1

**Comment by yuriizubkov** [comment] 2020-10-08 17:09
I'm using iOS 14.0.1 as well. I'll check it again on v5-master branch.
Meanwhile, can you please post here how you receiving MIDI, whole function receivedMIDINoteOn with declaration?

**Comment by gilhadas** [comment] 2020-10-08 17:23
func receivedMIDINoteOn(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel, portID: MIDIUniqueID?, offset: MIDITimeStamp) {

        midiSignalReceived = true

        midiReceiverDelegate?.onReceiverNoteOn(Int(noteNumber),noteName: NoteData.midiToName(note: Int(noteNumber)), velocity: velocity,channel: channel)

    }

**Comment by yuriizubkov** [comment] 2020-10-08 17:52
I just installed v5-master from the Swift packages and test it with my app on iOS with no issues.

Maybe try to call your delegate from the main thread:
```
func receivedMIDINoteOn(noteNumber: MIDINoteNumber, velocity: MIDIVelocity, channel: MIDIChannel, portID: MIDIUniqueID?, offset: MIDITimeStamp) {
    DispatchQueue.main.async {
        self.midiSignalReceived = true
        self.midiReceiverDelegate?.onReceiverNoteOn(Int(noteNumber),noteName: NoteData.midiToName(note: Int(noteNumber)), velocity: velocity, channel: channel)
    }
}
```

**Comment by gilhadas** [comment] 2020-10-08 18:04
It doesn't reach it at all, I have breakpoint in the method, and it doesn't stop.

**Comment by gilhadas** [comment] 2020-10-08 18:19
in openInput(uid inputUID: MIDIUniqueID) {
... it call 
self.handleMIDIMessage( ... 
and inside it there is a loop 
for listener in listeners {
and the listeners is empty
while in class MIDI, line 77 
 listener.receivedMIDINotification(notification: $0.pointee)
listeners is not empty

**Comment by yuriizubkov** [comment] 2020-10-08 19:06
Just for information, I have not changed the event subscription logic in this commit.
If there are no subscribers in the collection, then they probably are not there at this particular time. 
Do you subscribe to events before or after the opening of the port?

One more thought.
I am using the MIDI class in my singleton wrapper class in the application. Therefore, I have one MIDI() instance for the entire application. I don't know how you subscribe to MIDI events, but is it possible that you are creating multiple MIDI class instances? If you see the message "Initializing MIDI" in the logs more than 1 time - this is not right, for example. A race condition is also possible, because MIDI works in a separate priority thread.

Maybe you can make a test project without sensitive information that you can share so I can reproduce this?
More information needed.

**Comment by gilhadas** [comment] 2020-10-08 19:27
Thanks Yurii,
That did help.
I moved the MIDI to other place . this cause the problem.
now when using MIDI.sharedInstance all issues are solved.
I suggest to block the option to create a MIDI object , so it will be clear to use MIDI.sharedInstance.

**Comment by yuriizubkov** [comment] 2020-10-08 19:31
@gilhadas Nice to hear! So I guess you can close this issue.

**Comment by gilhadas** [comment] 2020-10-08 19:45
yes

**Closed** 2020-10-08 19:45 UTC

**Comment by aure** [comment] 2020-10-08 20:12
Thanks @yuriizubkov
