### ISSUE TITLE
AKFrequencyTracker / AKMicrophone not working on device

### ISSUE THREAD

**Issue by holeg** [audiokit/AudioKit#725] opened 2017-02-03 22:08 UTC
I have an objective C app where I included AudioKit to detect pitch. Everything works well on simulator and on my Mac App, but not on the device (tested on iPhone 7 plus and iPad Pro).

Here is the code:

#import "KJTuner.h"
#import <AudioKit/AudioKit.h>
#import <AudioKit/AudioKit-Swift.h>

@interface KJTuner()

@property (nonatomic,strong) AKMicrophone *microphone;
@property (nonatomic,strong) AKFrequencyTracker *tracker;
@property (nonatomic,strong) AKBooster *silence;
@property (nonatomic,strong) NSTimer *timer;
@property (nonatomic) NSTimeInterval updateInterval;

@end

@implementation KJTuner

- (instancetype)init
{
    self = [super init];
    if (self) {
        _updateInterval = 0.03;
        AKSettings.audioInputEnabled = YES;
        _microphone = [[AKMicrophone alloc] init];
        _tracker = [[AKFrequencyTracker alloc] init:_microphone hopSize:512.0 peakCount:20.0];
        _silence = [[AKBooster alloc] init:_tracker gain:0];
    }
    return self;
}

- (void) start
{
    AudioKit.output = _silence;
    [AudioKit start];
    [_microphone start];
    [_tracker start];
    
    [_timer invalidate];
    _timer = [NSTimer scheduledTimerWithTimeInterval:_updateInterval target:self selector:@selector(handleTimer) userInfo:nil repeats:YES];
    
}

- (void) stop
{
    [_microphone stop];
    [_tracker stop];
    [_timer invalidate];
}

- (void) handleTimer
{
        NSLog(@"_tracker.amplitude:%f",_tracker.amplitude);
}

@end

 I requested permission for Microphone:

[[AVAudioSession sharedInstance] requestRecordPermission:^(BOOL granted) {
            if (granted) {
                NSLog(@"Permission granted");
            }
            else {
                NSLog(@"Permission denied");
            }
        }];

And I set also the audio session to AVAudioSessionCategoryPlayAndRecord

In the console it always logs (see handleTimer function)

2017-02-03 23:00:19.651376 xxx[4782:2943221] _tracker.amplitude:0.000000
2017-02-03 23:00:19.682293 xxx[4782:2943221] _tracker.amplitude:0.000000
2017-02-03 23:00:19.710651 xxx[4782:2943221] _tracker.amplitude:0.000000

When I run it on the simulator it works perfect.

Maybe I miss something and it is not a bug ....

**Comment by aure** [comment] 2017-02-04 00:56
So, the included microphone analysis project works for me on my phone.  Can you try to run it on your phone to see if it works for you?

**Comment by aure** [comment] 2017-02-04 00:57
I'm also willing to test your app out directly if you can share the code.

**Comment by holeg** [comment] 2017-02-04 08:46
The included microphone analysis project does not work on my iPhone 7+ I used newest code from GIT.
When starting the App I was asked for mic permission, which I allowed. But then same happens as with my Objective C App. No amplitude or frequency is shown.
Same thing on my iPad Pro 12.9 inch. But it works on simulator!
I also tried it with the ear pods and other external mic. Same result.
But the App "Partita" (Downloaded from AppStore), which is based on AudioKit works perfectly.

**Comment by maznoum** [comment] 2017-02-04 17:29
I tried yesterday with the 3.5.2 release on on iPhone SE and an iPad mini 2 with the same results as holeg: no sound received on the devices and works on the simulator.

**Comment by aaronhillier123** [comment] 2017-02-04 22:49
I got the same result as they did on 3.5.2

**Comment by maznoum** [comment] 2017-02-04 23:16
I just tried the Microphone Analysis app on 3.5.1 and it works on the device.

**Comment by aure** [comment] 2017-02-05 01:30
Huh, my iPad Pro 12.9 is working just fine, but my iPhone 7 Plus does not.  At least now I can start to debug.

**Comment by aure** [comment] 2017-02-05 01:49
@maznoum Can you double check the iPad Pro to see if you have the same situation as me?

**Comment by aure** [comment] 2017-02-05 03:21
I can confirm that AudioKit v3.5.1 does not have this problem so that narrows it down.

**Comment by aure** [comment] 2017-02-05 04:12
Fixed in develop, use AudioKit 3.5.1 until AudioKIt 3.5.3 comes out if you are using the precompiled framework.

**Closed by aure** 2017-02-05 04:12 UTC
