### ISSUE TITLE
Crash in MidiMonitor example project

### ISSUE THREAD

**Issue by ClayApps** [audiokit/AudioKit#303] opened 2016-02-22 23:23 UTC
Built everything per the read me ok. Ran the MidiMonitor example and hooked up Session 1 in the Sym, it crashed parsing a midi note, oddly it parsed some Sys Ex no problem.

Console from App:
MIDI Enabled
created client
Opening MIDI In
SourceCount: 1
created midiInPort at Session 1
MIDI Notify, messageId= 4
MIDI Notify, messageId= 1
MIDI System Command: Sysex
MIDI System Command: Sysex
fatal error: unexpectedly found nil while unwrapping an Optional value

Here's the line:
```swift
 fillWithStatus(status!, channel: channel, byte1: packet.data.1, byte2: packet.data.2)
```

Here's the method:

```swift
init(packet: MIDIPacket) {
        if packet.data.0 < 0xF0 {
            let status = AKMIDIStatus(rawValue: Int(packet.data.0) >> 4)
            let channel = UInt8(packet.data.0 & 0xF)
            fillWithStatus(status!, channel: channel, byte1: packet.data.1, byte2: packet.data.2)
        } else {
            if(packet.data.0 == AKMIDISystemCommand.Sysex.rawValue){ //if is sysex
                internalData = [] //reset internalData
                //voodoo
                let mirrorData = Mirror(reflecting:packet.data)
                var i = 0
                for (_, value) in mirrorData.children{
                    internalData.append(UInt8(value as! UInt8))
                    i++
                    if(value as! UInt8 == 247){
                        break;
                    }
                }//end voodoo
            }else{
                fillWithCommand(
                    AKMIDISystemCommand(rawValue: packet.data.0)!,
                    byte1: packet.data.1,
                    byte2: packet.data.2)
            }
        }
    }```

**Comment by ClayApps** [comment] 2016-02-23 19:13
Update, it's actually crashing processing the SysEx on the second message:

```Hex
F0 41 00 14 12 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 0D 00 
00 0D 00 00 00 00 00 2C 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 3A F7 

F0 41 00 14 12 00 02 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 31 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 18 00 
32 00 00 0C 00 00 00 34 64 2F 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 30 F7 
```

**Comment by aure** [comment] 2016-04-29 20:43
I can't reproduce this one either.  Is it possible this is fixed in newer AudioKit?

**Comment by aure** [comment] 2016-04-30 19:59
Feel free to reopen this issue if you can reproduce with the develop branch of AK.  Thanks!

**Closed by aure** 2016-04-30 19:59 UTC
Labels: question

**Comment by ClayApps** [comment] 2016-05-02 18:15
Looking at some of your recent checkins you probably have this covered.
