### ISSUE TITLE
CompletionHandler: Unable to start play with new startTime

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/AudioKit#2672] opened 2022-02-14 10:59 UTC
I am trying to make the AudioKit completionHandler play with a new start time, like this:

func completionHandler () {
        pickNextSegment()
        player.play(from: playbackStartTime, to: playbackEndTime, completionCallbackType: .dataConsumed)
}

However, the new playbackStartTime is not respected, and the player just keeps looping over the segment that was set with the initial play command.

**To Reproduce**
From the completionHandler, call player.play with a new startTime/EndTime.

**Expected behavior**
I expect the player to play using the new startTime and endTime values.

**Details (please complete the following information):**
 - MacOS
 - OS: 12.2
- The bug was introduced recently, not sure exactly in which AudioKit version.
I have tried both version 5.3.3 and the develop branch.

**Additional context**
I have attached a demo app. I have named it SegmentPlayer, but it is not using the new MultiSegmentAudioPlayer (it's on my list).

Complied App for macOS:
[SegmentPlayer.zip](https://github.com/AudioKit/AudioKit/files/8059961/SegmentPlayer.zip)

Just press Play, and you can see that when it reaches the end of section 1, it keeps looping section 1 rather than jumping to the next section.

Source code:
[SegmentPlayer Source.zip](https://github.com/AudioKit/AudioKit/files/8059993/SegmentPlayer.Source.zip)

**Comment by NickCulbertson** [comment] 2022-02-14 12:29
I'm not sure if it is a bug but you can get around it by putting your next play call in an async task. 

`DispatchQueue.main.async {
            self.player.play(from: self.playbackStartTime, to: self.playbackEndTime, completionCallbackType: .dataConsumed)
}`

**Comment by ShowtimeSoft** [comment] 2022-02-14 12:49
Thanks a lot! Now the "playNext" works.
Also not sure of it is a bug.

I've compiled the demo app with the async call:
[SegmentPlayer.zip](https://github.com/AudioKit/AudioKit/files/8060786/SegmentPlayer.zip)

As you see, the player.getCurrentTime() is now all over the place.
But I guess this is another topic.

**Comment by emurray2** [comment] 2022-02-27 20:02
> Thanks a lot! Now the "playNext" works.
> Also not sure of it is a bug.
> 
> I've compiled the demo app with the async call:
> [SegmentPlayer.zip](https://github.com/AudioKit/AudioKit/files/8060786/SegmentPlayer.zip)
> 
> As you see, the player.getCurrentTime() is now all over the place.
> But I guess this is another topic.

Yes, I'd like to get to fixing some of the player stuff this week. It appears some changes I made a little bit ago have led to some unexpected behavior. However, once we get the bugs worked out, the new system is more organized with Node Status types.

This way the player can only have one playback status at a time (i.e. playing, paused, or stopped). In many previous issues, I've noticed sometimes it would have multiple states which created undefined behavior.

The edit times are still a work in progress, and it may be due to the completion handler, but I'll work on it asap. Feel free to jump in the code if I don't get to it soon enough.

**Comment by ShowtimeSoft** [comment] 2022-02-28 10:19
Thanks for the reply.

I have filed another issue related to the completionHandler resulting in an unrecoverable state when the audio is buffered.

**Comment by emurray2** [comment] 2022-03-17 12:50
@ShowtimeSoft My apologies on forgetting about this. I had some time this morning to look at it, and I believe I got your program to work. Please test with the new changes, and let me know what you think :) !

**Comment by aure** [comment] 2022-03-19 01:57
Closing for now, feel to continue to correspond here though.

**Closed by aure** 2022-03-19 01:57 UTC
