### ISSUE TITLE
Record with AKRecorder

### ISSUE THREAD

**Issue by YoanGJ** [audiokit/AudioKit#323] opened 2016-03-29 13:57 UTC
I'm trying to record with the new AKAudioRecorder object from the develop branch but It doesn't works.

I use the initialiser AKAudioRecorder(NSTemporaryDirectory() + "record.wav") but it seems that AKRecorder doesn't create the file if this one doesn't exist, right ?
Because when I want to play the file by passing the same path to an AKAudioPlayer (after doing a .record and a .stop from my AKAudioRecorder object), I have a segfault...

How can I do to create a .wav file where AKAudioRecorder can write on ?

**Comment by aure** [comment] 2016-03-29 17:54
I don't think that creating the audio file to record to should be the recorder's responsibility.

Why not just create a container recording.wav in your project that you will overwrite:

let bundle = NSBundle.mainBundle()
let file = bundle.pathForResource("recording", ofType: "wav")

Aure

**Comment by YoanGJ** [comment] 2016-03-30 07:18
Mmmh I tried but pathForResource returns me nil in that case...

**Comment by aure** [comment] 2016-03-30 21:51
Did you put a placeholder file in there and make sure to set the target membership to be your project?

**Comment by aure** [comment] 2016-03-30 21:52
Since this is not really an AudioKit issue, but iOS stuff, I am going to close the issue.  But, we can still continue to communicate on this thread even after the issue is closed.

**Closed by aure** 2016-03-30 21:52 UTC
