### ISSUE TITLE
AudioPlayer crashes application

### ISSUE THREAD

**Issue by myreauks** [AudioKit/AudioKit#2868] opened 2023-10-15 14:52 UTC
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 15

### Description

When loading a mono wav to Audioplayer first it plays fine. If I use the same player to load a stereo wav file and try to play it again, the player crashes the application.

Here is the relevant code.

First time loading the mono file:
```swift
    var audioFile: AVAudioFile?
    
    var player = AudioPlayer()

guard let url = Bundle.main.resourceURL?.appendingPathComponent(file) else { return }
        do {
            
            audioFile = try AVAudioFile(forReading: url)
            
            try player.load(url: url, buffered: true)
            
        } catch {
            Log("Could not load: \(fileName)")
        }
    }
```

Then loading the stereo file:
```swift
guard let url = Bundle.main.resourceURL?.appendingPathComponent(file) else { return }
        do {
            
            audioFile = try AVAudioFile(forReading: url)
            
            try player.load(url: url, buffered: true)
            
        } catch {
            Log("Could not load: \(fileName)")
        }
    }
```

Trying to play the player after this crashes the application.

### Crash Logs, Screenshots or Other Attachments (if applicable)

AVAEInternal.h:76 required condition is false: [AVAudioPlayerNode.mm:734:ScheduleBuffer: (_outputFormat.channelCount == buffer.format.channelCount)]

**Comment by NickCulbertson** [comment] 2023-10-20 14:21
Yes, I confirmed the issue. After the player is created the channel count isn't updated when changing from a stereo to mono file and vice versa. Until the issue is addressed the best bet is to stick with stereo audio.

**Comment by NickCulbertson** [comment] 2023-10-20 14:28
I did find this workaround: 

```guard let url = Bundle.module.resourceURL?.appendingPathComponent("Samples/\(filename)"),
              let buffer = try? AVAudioPCMBuffer(url: url)
        else {
            Log("failed to load sample", filename)
            return
        }
        conductor.player.isLooping = true
//Set the player file here to get the correct file format
        conductor.player.file = try? AVAudioFile(forReading: url)
        conductor.player.buffer = buffer```

**Comment by myreauks** [comment] 2023-10-20 19:10
> I did find this workaround:
> 
> ```
>        guard let url = Bundle.module.resourceURL?.appendingPathComponent("Samples/\(filename)"),
>               let buffer = try? AVAudioPCMBuffer(url: url)
>         else {
>             Log("failed to load sample", filename)
>             return
>         }
>         conductor.player.isLooping = true
> //Set the player file here to get the correct file format
>         conductor.player.file = try? AVAudioFile(forReading: url)
>         conductor.player.buffer = buffer
> ```
> 
> This should fix the issue. The problem is that the buffer is being changed, but the format from the new audio file isn't observed.

Thanks for the tip!
What does the line 'conductor.player.isLooping = true' do here besides the obvious? Is it somehow resetting the buffer format?

Btw. I love your Youtube tutorials! They really helped me kickstart development with Audiokit!

**Comment by NickCulbertson** [comment] 2023-10-20 19:14
Thanks! That's awesome to hear!

That looping line just loops the audio. You can leave that out, unless you want audio looping. It was copied over from the Cookbook where I was testing out the issue.

**Comment by myreauks** [comment] 2023-10-20 19:25
For whatever reason, that workaround did not work for me, it is still giving the exact same error.
`AVAEInternal.h:76 required condition is false: [AVAudioPlayerNode.mm:734:ScheduleBuffer: (_outputFormat.channelCount == buffer.format.channelCount)]`

**Comment by NickCulbertson** [comment] 2023-10-20 21:23
I got that error too before adding that line. It could be something about the audio files.

Are you on the latest version of AudioKit? If you can make a small example project I’ll take a look.

**Comment by NickCulbertson** [comment] 2023-10-20 23:13
Also, make sure to call `player.stop()` before loading the new file/buffer.

**Comment by myreauks** [comment] 2023-10-21 09:36
Hi!
I uploaded an example here:
[https://github.com/myreauks/audioplayer-example](url)

I can make it crash by first pressing the play button. Then press the "Change file to stereo" and play again and the crash will happen.

**Comment by NickCulbertson** [comment] 2023-10-21 11:53
Thanks for posting the project. I think you must have some uncommitted changes on the example repo. I'm seeing an empty Xcode project.

**Comment by myreauks** [comment] 2023-10-21 15:51
Whoops, still learning this stuff. It should be there now.

**Comment by NickCulbertson** [comment] 2023-10-21 16:08
Interestingly if you load the stereo file first, it does not crash.

When the player creates the mono buffer it makes the output stereo. I'm guessing by starting with a mono file it isn't working in reverse. I'll test a little more. The workaround for now is to load a stereo file first.

**Comment by NickCulbertson** [comment] 2023-10-21 16:46
Try this out ```

//  ContentView.swift
//  audioplayertest


import SwiftUI
import AVFoundation
import AudioKit

class PlayerConductor: ObservableObject, HasAudioEngine {
    
    let engine = AudioEngine()
    let mixer = Mixer()
    
    var audioFile: AVAudioFile?
    
    var player = AudioPlayer()
    
    init() {
        engine.output = player
        loadFile(filename: "clap_mono.wav")
    }
    
    func loadFile(filename: String) {
        player.stop()
        guard let url = Bundle.main.resourceURL?.appendingPathComponent("Samples/\(filename)"),
              let buffer = try? AVAudioPCMBuffer(url: url)
        else {
            Log("failed to load sample", filename)
            return
        }
        player.file = try? AVAudioFile(forReading: url)
        player.buffer = buffer
        print("Channel count for AVAudioPlayerNode")
        print(player.playerNode.outputFormat(forBus: 0).channelCount)
    }
    
    func play() {
        player.play()
    }
    
    func stop() {
        player.stop()
    }
}

struct ContentView: View {
    @StateObject var conductor = PlayerConductor()
    
    var body: some View {
        VStack {
            HStack {
                Button(action: {conductor.play()}) {
                    Image(systemName: "play.fill")
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
                Button(action: {conductor.stop()}) {
                    Image(systemName: "stop.fill")
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
            }
            Button(action: {conductor.loadFile(filename: "clap_stereo.wav")}) {
                Text("Change file to stereo")
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)

            
            Button(action: {conductor.loadFile(filename: "clap_mono.wav")}) {
                Text("Change file to mono")
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)
        }
        .padding()
        .onAppear {
            conductor.start()
        }
        .onDisappear {
            conductor.stop()
        }
    }
}

#Preview {
    ContentView()
}
```

**Comment by NickCulbertson** [comment] 2023-10-21 16:47
I think the file needed to be loaded after the output was set.

**Comment by NickCulbertson** [comment] 2023-10-21 22:52
Also unrelated, but worth mentioning: 

`.onDisappear` isn't called when an app is closed. That method is mostly used when a navigation view is dismissed. Instead look into `.onChange(of: scenePhase)`

Calling `conductor.stop()` might lead to unwanted results, because you have that method name in both the `PlayerConductor` class and its `HasAudioEngine` protocol.

**Comment by myreauks** [comment] 2023-10-22 15:05
Thanks!
Attaching the player to the output before loading a file seemed to fix the crash. I wonder why that is...

Thanks for the other tip too, I will look into it for sure.

**Comment by NickCulbertson** [comment] 2023-10-22 23:38
```
I noticed that the buffer length doesn't seem to update somehow with the code you posted. If the first file is shorter than the second file loaded, the second file will stop playing mid-file.
```

That is annoying and definitely a separate issue. 

What about playing the audio file rather than the scheduled buffer?

```
func loadFile(filename: String) {
        player.stop()
        try! player.load(url: (Bundle.main.resourceURL?.appendingPathComponent("Samples/\(filename)"))!)
        
//        guard let url = Bundle.main.resourceURL?.appendingPathComponent("Samples/\(filename)"),
//              let buffer = try? AVAudioPCMBuffer(url: url)
//        else {
//            Log("failed to load sample", filename)
//            return
//        }
//        player.file = try? AVAudioFile(forReading: url)
//        player.buffer = buffer
//        print("Channel count for AVAudioPlayerNode")
//        print(player.playerNode.outputFormat(forBus: 0).channelCount)
    }
```

**Comment by NickCulbertson** [comment] 2023-10-22 23:51
Now I'm seeing I'm the one that added the buffered bit in the first place. That was pulled from the Cookbook example.

**Comment by NickCulbertson** [comment] 2023-10-22 23:58
You can add `buffered: true` at the end of the expression if the audio file is set after the engine's output is set. The order doesn't seem to matter or crash if `buffered: false`.

**Comment by myreauks** [comment] 2023-10-23 14:26
Great, that seems to fix it! Thanks!
It seems to be very important to add all the node connections before loading any files.
Perhaps it is not a bug after all but just the way it is designed.

**Comment by NickCulbertson** [comment] 2023-10-23 17:24
Yeah, maybe so. The Audio Player class is a bit of a tangled mess, and I think there is still an issue with resetting buffer length and format based on the tests.

I'll go ahead and close this since using `player.load(url:` seems to be an adequate substitute for now.

**Closed by NickCulbertson** 2023-10-23 17:24 UTC
Labels: bug
