### ISSUE TITLE
Error in Testflight Submission

### ISSUE THREAD

**Issue by afnan-ahmad** [audiokit/AudioKit#560] opened 2016-09-20 13:06 UTC
I'm using AudioKit v3.3 in my app, I'm submitting build on iTunes Connect for Testflight and getting ITC.apps.preReleaseBuild.errors.invalidBinary error, while Apple send following email:

> We have discovered one or more issues with your recent delivery for "App". To process your delivery, the following issues must be corrected:
> 
> Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

Any idea how to fix this issue?

**Comment by themichael123** [comment] 2016-09-20 14:07
Same issue here.

**Comment by afnan-ahmad** [comment] 2016-09-20 14:12
@themichael123 You can try following solution temporarly, I've success while removing following lines from `Info.plist` inside `AudioKit.framework` package.

```
<key>CFBundleSupportedPlatforms</key>
<array>
<string>iPhoneSimulator</string>
</array>
```

**Comment by themichael123** [comment] 2016-09-20 16:49
Thank you @afnan-ahmad ! It works.

**Comment by aure** [comment] 2016-09-20 17:51
Hey guys, love it that you helped each other out before I could chime in.  We'll try to fix this on our end for the next release.  Stephane is the man for these kind of issues so I let him know.

**Comment by megastep** [comment] 2016-09-21 10:36
I just pushed a fix in the fix-frameworks.sh script that should take care of it, you can check it out on the level branch. It is basically a one-liner that calls `plutil` to remove these lines.

I may consider simply re-uploading manually patched frameworks for the current release, are you guys using CocoaPods or the binaries we ship directly?

**Comment by megastep** [comment] 2016-09-21 10:41
Another thing that occurred to me is that this may be caused by the fact that our scripts build the simulator framework first, and then append the native slices to it. It might be a good idea to try to reverse the order here, so that we start from a valid device framework.

**Comment by afnan-ahmad** [comment] 2016-09-21 10:42
@megastep thanks! :)

I'm using binary in my project as I was having issue with CocoaPods to run fix-frameworks.sh script.

But I can compile new binary from develop branch!

**Comment by aure** [comment] 2016-09-21 16:33
We can keep this conversation going, but I'd like to mark the issue as closed when everyone is satisfied.

**Comment by themichael123** [comment] 2016-09-21 19:18
Sure, thank you.

**Closed** 2016-09-21 19:40 UTC
