### ISSUE TITLE
iOS13 Crash - Error: Failed to fill complex buffer in float converter ('insz')

### ISSUE THREAD

**Issue by mlostekk** [AudioKit/AudioKit#1895] opened 2019-10-11 07:24 UTC
I am using AudioKit 4.8 like this

```
class AudioKitWrapper {

    /// The main output mixer (after the amplitude tracker)
    private let masterMixer:  AKMixer

    /// The audio input
    private var microphone:   EZMicrophone?

    /// Construction
    init() {
        // global settings
        AKAudioFile.cleanTempDirectory()
        AKSettings.defaultToSpeaker = true
        AKSettings.enableRouteChangeHandling = true
        AKSettings.enableCategoryChangeHandling = true
        AKSettings.disableAVAudioSessionCategoryManagement = true
        AKSettings.audioInputEnabled = true
        AKSettings.playbackWhileMuted = false
        #if DEBUG
            AKSettings.enableLogging = AppConfig.AudioConfig.debugLogEnabled
        #endif
        // main mixer
        masterMixer = AKMixer()
    }

    /// Start up audiokit
    func startEngine(with audioInput: Bool) throws {
        // connect main nodes
        AudioKit.output = masterMixer
        // input
        microphone?.delegate = nil
        microphone = nil
        if audioInput {
            AKSettings.enableEchoCancellation = true
            let sizeOfFloat = UInt32(MemoryLayout<Float>.stride)
            microphone = EZMicrophone(microphoneDelegate: self,
                                      with: AudioStreamBasicDescription(mSampleRate: Float64(mirgaFactory.getSampleRate()),
                                                                        mFormatID: kAudioFormatLinearPCM,
                                                                        mFormatFlags: kLinearPCMFormatFlagIsFloat |
                                                                                      kAudioFormatFlagsNativeEndian |
                                                                                      kAudioFormatFlagIsPacked |
                                                                                      kAudioFormatFlagIsNonInterleaved,
                                                                        mBytesPerPacket: sizeOfFloat,
                                                                        mFramesPerPacket: 1,
                                                                        mBytesPerFrame: sizeOfFloat,
                                                                        mChannelsPerFrame: 1,
                                                                        mBitsPerChannel: sizeOfFloat * 8,
                                                                        mReserved: 0),
                                      startsImmediately: false)
        }
        // start
        try AKSettings.session.setCategory(.playAndRecord, mode: .measurement, options: .defaultToSpeaker)
        try AudioKit.start()
        microphone?.startFetchingAudio()
        Log.d("~~~ AudioKit: started")
    }

    /// Stop engine
    func stopEngine() throws {
        try AudioKit.stop()
        microphone?.stopFetchingAudio()
        Log.d("~~~ AudioKit: stopped")
    }

    /// Attach output
    func attach(audioPlayer: AKAudioPlayer) {
        audioPlayer >>> masterMixer
    }

    /// Reset
    func reset() {
        masterMixer.detach()
        Log.d("~~~ AudioKit: reset")
    }

}

/// Handle EZMicrophone input
extension AudioKitWrapper: EZMicrophoneDelegate {

    /// Playing state changed
    func microphone(_ microphone: EZMicrophone!, changedPlayingState isPlaying: Bool) {
        Log.i("playing state - \(isPlaying)")
    }

    /// Device changed
    func microphone(_ microphone: EZMicrophone!, changedDevice device: EZAudioDevice!) {
        Log.i("device - \(String(describing: device))")
    }

    /// Audio stream description
    func microphone(_ microphone: EZMicrophone!, hasAudioStreamBasicDescription audioStreamBasicDescription: AudioStreamBasicDescription) {
        Log.i("stream - \(audioStreamBasicDescription)")
    }

    /// Input buffer handling
    func microphone(_ microphone: EZMicrophone!,
                    hasAudioReceived buffer: UnsafeMutablePointer<UnsafeMutablePointer<Float>?>!,
                    withBufferSize bufferSize: UInt32,
                    withNumberOfChannels numberOfChannels: UInt32,
                    atTime timestamp: UnsafePointer<AudioTimeStamp>!) {
        writeSamplesIntoCircularBuffer(buffer[0]!, bufferSize, timestamp)
    }
}
```

# iOS13 - iPhone7

Its crashing with this log

```
2019-10-11 09:37:01.895794+0200 WyntonHost[555:135079] AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""
2019-10-11 09:37:01.917118+0200 WyntonHost[555:135079] AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""
2019-10-11 09:37:01.938441+0200 WyntonHost[555:135079] AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""
Error: Failed to fill complex buffer in float converter ('insz')

Process finished with exit code 255
```

# iOS13 - iPadAir2

I am getting this log messages without a crash (hundreds of them, i assume per audio frame)

```
2019-10-11 09:34:07.165282+0200 WyntonHost[376:18541] AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""
2019-10-11 09:34:07.187762+0200 WyntonHost[376:18541] AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""
2019-10-11 09:34:07.211279+0200 WyntonHost[376:18541] AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""
```

# iOS12 - iPhone6

I am getting this log messages without a crash (hundreds of them, i assume per audio frame)

```
2019-10-11 09:31:59.114901+0200 WyntonHost[537:96101] 55: EXCEPTION (-1): ""
2019-10-11 09:31:59.138013+0200 WyntonHost[537:96101] 55: EXCEPTION (-1): ""
2019-10-11 09:31:59.161233+0200 WyntonHost[537:96101] 55: EXCEPTION (-1): ""
```

**Any idea where this log message is coming from?**

**Comment by mlostekk** [comment] 2019-10-11 08:36
oh, had some formatting issues -> fixed.

Well yes, on ios 13 it leads to the same thing, but only on iphone7 (not ipadair2). This indicates that the default sample rate is wrongly set. (iphone7 uses 48k by default).

The iOS12 logs are something worth to mention maybe

**Comment by xieliweiparkman** [comment] 2019-10-31 19:07
I also have this problem for iPhoneX, iOS 13.1.3

**Comment by fiazhussain43** [comment] 2019-11-06 05:45
I also have this problem for iPhoneX, iOS 13.1.3

**Comment by fiazhussain43** [comment] 2019-11-06 05:45
I also have this problem for iPhoneXs max, iOS 13.1.3

**Comment by RWOverdijk** [comment] 2019-11-06 13:08
iPhone 11 Pro, iOS 13.2.

Weird.

**Comment by aure** [comment] 2019-11-22 00:50
Can anyone post the project that you're using that exhibits the behavior? We'll need something to work on to reproduce this problem. Closing until someone can provide that.

**Comment by ashishkeshan** [comment] 2019-11-22 00:59
@aure try this, I had posted it at the top of the previous thread I had created at #1873 
https://github.com/ashishkeshan/TestEZAudioBug

**Comment by aure** [comment] 2019-11-22 01:03
Looked at the project. Doesn't even have AudioKit in it. I'm looking more towards deprecated EZAudio in AudioKit anyway, so I don't have time to debug it.

**Closed by aure** 2019-11-22 01:03 UTC

**Comment by crontab** [comment] 2020-06-24 23:09
In case someone is still looking for this error: in my case it was happening on iOS 13.5 (but not under Catalyst) because I had two competing remote audio units initialized and running: RemoteIO and VoiceProcessingIO.

Interestingly, echo cancellation worked fine even when I sent some audio via RemoteIO and got mic input via VoiceProcessingIO. However this is the situation when you see repeated exception messages on iOS:

`AUBuffer.h:61:GetBufferList: EXCEPTION (-1) [mPtrState == kPtrsInvalid is false]: ""`

The fix is to use VoiceProcessingIO for both input and output. In this case though you will get lower quality mono sound on output regardless of what format specification was on the output bus (0).

This doesn't happen on Catalyst though, so may be a bug in iOS CoreAudio. Hope this helps someone.
