### ISSUE TITLE
Xcode 12.0 project fails to build after upgrading to AudioKit 4.11 from 4.10 via CocoaPods

### ISSUE THREAD

**Issue by b-hutchison** [AudioKit/AudioKit#2269] opened 2020-09-17 23:13 UTC
**Configuration:** 
Catalina 10.15.6 (19G2021)
Xcode 12.0 (12A7209)
AudioKit 4.11 updated from 4.10 in project using CocoaPods 1.9.3

**Issue**
Existing project now fails to build, reporting this error:

“Failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced”

**pod update** reported success installing AudioKit, but did complain about not being able to read the license file.
[!] Unable to read the license file `LICENSE` for the spec `AudioKit (4.11)`

**Comment by megastep** [comment] 2020-09-17 23:15
Duplicate of issue #2267

**Closed** 2020-09-17 23:15 UTC
