### ISSUE TITLE
AKAudioPlayernode.play crash

### ISSUE THREAD

**Issue by mlostek** [AudioKit/AudioKit#1469] opened 2018-08-17 09:40 UTC
I am having a strange crash within the `AKAudioPlayer`. It crashes when i setup, play 4 times, teardown, then setup again and the first play crashes.
 
It crashes with 
```
AKAudioPlayer.swift:startTime:171:AKAudioPlayer.startTime = 0.0, startingFrame: 0
AKAudioPlayer.swift:updatePCMBuffer():564:read 21888 frames into buffer
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

with this implementation:

```swift
import Foundation
import AudioKit

@objc(MetronomeSoundProcessor)
class MetronomeSoundProcessor: NSObject {

  var player: AKAudioPlayer?

  func setup() -> NSError? {
    do {
      let file = try AKAudioFile(readFileName: "ClickDown.wav")
      player = try AKAudioPlayer(file: file)
      AudioKit.output = player
      try AudioKit.start()
      return nil
    } catch let error as NSError {
      return error
    }
  }

  @objc func play() {
    player?.play()
  }

  @objc func tearDown() {
    player?.disconnect()
    player = nil
  }
}
```

![bildschirmfoto 2018-08-17 um 11 39 41](https://user-images.githubusercontent.com/39261122/44259633-5b51d200-a212-11e8-8403-d8f391231fb7.JPG)

Any ideas what i am doing wrong?

**Comment by aure** [comment] 2018-08-21 23:47
Just acknowledging that this is also on StackOverflow: https://stackoverflow.com/questions/51892746/akaudioplayernode-play-crash  

Could you share a project with me so I can run it myself?

**Comment by mlostek** [comment] 2018-08-29 07:40
Yes, i wrote that stackoverflow question too.

Unfortunately I dont have any project to share. But i try to paste the most relevant code. My assumption is that I am using `AudioKit.start()` and `AudioKit.stop()` from 2 different locations. The `MetronomeSoundProcessor` above is triggered from an background thread. And then we have another module starting / stopping the AudioKit engine. Might this be an issue?

**Comment by mlostek** [comment] 2018-08-29 16:05
I have just moved out the triggering of `play` into the main thread and now i am seeing a proper error message which says

`Exception 'player started when engine not running' was thrown while invoking run_precounter on target MetronomeTimer with params` 

But when i check `Audiokit.engine.running` shortly before the crash, its set to `true`

Any hints?

**Comment by aure** [comment] 2018-08-29 17:07
A few people have noticed that relying on the engine.running property is suspect.  Can you share a project?

**Comment by mlostekk** [comment] 2018-08-30 07:34
Unfortunately i cannot reproduce it with a fresh setup project, digging into legacy code now...

**Comment by warpling** [comment] 2018-10-01 16:16
@aure pretty sure this is the bug I've mentioned before. Checking if engine is running doesn't help as mentioned. I want to think it's some sort of race condition or has do with a competing system engine but I've been at a loss about this one for awhile. It seems to most often happen when AK's engine is forced to restart due to phone call, backgrounding, wireless headphones connecting etc.

**Comment by aure** [comment] 2018-10-06 04:47
Just closing until more information is provided. Perhaps best to start a new issue when you have more detail on where the problem happens and how to resolve.  Thanks!

**Closed** 2018-10-06 04:46 UTC
