### ISSUE TITLE
AKAppleSampler Memory Leak

### ISSUE THREAD

**Issue by robtize** [AudioKit/AudioKit#1310] opened 2018-04-07 16:58 UTC
Not exactly sure what's going on it's hard for me to debug. But ever since i've updated to AudioKit 4.2 from AudioKit 4.1 i've been experiencing a huge memory leak when loading and unloading samples with AKAppleSampler. I've reverted back to AudioKit 4.1 and i'm not seeing the leak this only happens with 4.2

**Comment by aure** [comment] 2018-04-07 18:35
Are you using the latest Xcode and Swift even with AudioKit 4.1?  Apple Sampler is a very thin wrapper to Apple's sampler so I am wondering if its not a bug in Apple's code.

**Comment by aure** [comment] 2018-04-07 18:37
This is why sometimes its better to do a question on StackOverflow than an issue, because there you might get more eyeballs that aren't familiar with AudioKit but know more about Apple Audio and potential bugs therein.

**Comment by robtize** [comment] 2018-04-07 18:40
Opps sorry about that, i'll be sure to use Github next time. As of now I haven't updated to the newest Xcode i'm still using 9.2. I can use AudioKit 4.1 with Xcode 9.2 everything is fine. With the exact same code base I just update my pod to AudioKit 4.2 and I get the memory leak

**Comment by robtize** [comment] 2018-04-07 18:41
//
//  TZAudioEngine.swift
//  Tize
//
//  Created by Robert on 3/5/18.
//  Copyright © 2018 Tize Music, Inc. All rights reserved.
//

import Foundation
import AudioKit

@objc open class TZAudioEngine: NSObject {
    static let EngineStartedNotificationName = Notification.Name("com.tize.engine.engine_started")
    static let EngineStoppedNotificationName = Notification.Name("com.tize.engine.engine_stopped")
    
    static let sharedManager = TZAudioEngine()
    public override init() {
        super.init()
        setupAudioSettings()
        startEngine()
    }
    
    //engine state
    var isPlaying: Bool {
        if let sequencer = sequencer {
            return sequencer.isPlaying
        }
        return false
    }
    
    var isRecordingMidi: Bool = false
    var isRecordingAudio: Bool = false
    var isRecording: Bool {
        return isRecordingMidi || isRecordingAudio
    }
    
    //core data
    var coreDataManager = CoreDataManager.sharedInstance()
    var currentProject: Project?
    
    //audiokit
    var mixer: AKMixer?
    var sequencer: Sequencer?
    var metronomeNode: AKMIDISampler?
    var metronomeTrack: AKMusicTrack?
    var outputUnit: AVAudioUnitReverb?
    
    //sequencer
    var getCurrentPositionInBeats: Double {
        if let beats = sequencer?.currentPositionInBeats {
            if let songLength = currentProject?.actualSongLengthInBeats?.doubleValue {
                return beats.truncatingRemainder(dividingBy: songLength)
            }
            return beats
        }
        return 0
    }
    
    var getCurrentPositionInSeconds: Double {
        if let seconds = sequencer?.currentPositionInSeconds {
            if let songLengthInBeats = currentProject?.actualSongLengthInBeats?.doubleValue, let songLength = currentProject?.getTimeInSecondsFromTime(inBeats: CGFloat(songLengthInBeats))  {
                return seconds.truncatingRemainder(dividingBy: Double(songLength))
            }
            return seconds
        }
        return 0
    }
    
    //setup audio settings
    func setupAudioSettings() {
        AKSettings.enableRouteChangeHandling = true
        AKSettings.enableCategoryChangeHandling = true
        AKSettings.playbackWhileMuted = true
        AKSettings.defaultToSpeaker = true
        AKSettings.useBluetooth = true
        AKSettings.audioInputEnabled = true
        AKSettings.sampleRate = AVAudioSession.sharedInstance().sampleRate
    }
    
    //engine controls
    func startEngine() -> Bool {
        guard AudioKit.engine.isRunning == false else { return true }
        //setup mixer
        mixer = AKMixer()
        outputUnit = AVAudioUnitReverb()
        guard let mixer = mixer, let outputUnit = outputUnit, AVAudioSession.sharedInstance().currentRoute.outputs.count > 0 else { return false }
        outputUnit.wetDryMix = 0
        mixer >>> outputUnit
        AudioKit.output = AKNode(avAudioNode: outputUnit)
        
        do {
            try AudioKit.start()
            NotificationCenter.default.post(name: TZAudioEngine.EngineStartedNotificationName, object: nil)
            return true
        } catch {
            print("error starting engine")
            return false
        }
    }
    
    func playSong() {
        playSong(atTime: 0)
    }
    
    func pauseSong() {
        self.sequencer?.stop()
    }
    
    func playSong(atTime: CGFloat) {
        var time = atTime
        if ABLLinkManager.sharedInstance().isLinkEnabled {
            time = coreDataManager!.currentProject.getTimeInSecondsFromTime(inBeats: ABLLinkManager.sharedInstance().getQuantizedBeat(forLinkTime: time))
        }
        if isRecording && currentProject?.metronome?.boolValue == true {
            metronomeNode?.volume = 1
        } else {
            metronomeNode?.volume = 0
        }
        playAudioFiles(atTime: time)
        playSequencerAt(seconds: time)
        playSequencer()
    }
    
    func playSong(atBeat: CGFloat) {
        if let seconds = currentProject?.getTimeInSecondsFromTime(inBeats: atBeat) {
            playSong(atTime: seconds)
        }
    }
    
    func playAudioFiles(atTime: CGFloat) {
        stopAudioFiles()
        guard let tracks = currentProject?.tracks else { return }
        for track in tracks {
            guard let track = track as? Track, let pattern = track.pattern else { break }
            if track.loopAudio?.boolValue == true {
                track.audioPlayer?.buildAndPlayLoops(with: pattern, atTime: atTime)
            } else {
                track.audioPlayer?.playTime(inSeconds: atTime)
            }
        }
    }
    
    func playAudioFiles(atBeat: CGFloat) {
        if let seconds = currentProject?.getTimeInSecondsFromTime(inBeats: atBeat) {
            playAudioFiles(atTime: seconds)
        }
    }
    
    func playSequencerAt(seconds: CGFloat) {
        sequencer?.currentPositionInSeconds = TimeInterval(seconds)
    }
    
    func playSequencer() {
        do {
            try sequencer?.start()
        } catch {
            print("Error starting sequencer")
        }
    }
    
    func stopAudioFiles() {
        guard let tracks = currentProject?.tracks else { return }
        for track in tracks {
            guard let track = track as? Track else { break }
            track.audioPlayer?.stop()
        }
    }
    
    func clearProject() {
        isRecordingMidi = false
        isRecordingAudio = false
        stopAudioFiles()
        sequencer?.stop()
        removeUnitsFromTracks()
        removeUnitsFromSequencer()
        sequencer = nil
        mixer?.disconnectInput()
        outputUnit?.disconnectInput()
    }
    
    func removeUnitsFromSequencer() {
        guard let sequencer = sequencer else { return }
        for track in sequencer.tracks {
            track.destinationAudioUnit = nil
        }
    }
    
    func removeUnitsFromTracks() {
        guard let tracks = currentProject?.tracks else { return }
        for track in tracks {
            guard let track = track as? Track else { return }
            do {
                try track.samplerUnit?.loadWav("")
            } catch {
                print("Error loading empty wave to sampler unit")
            }
            track.samplerUnit?.destroyEndpoint()
            track.samplerUnit = nil
            track.audioPlayer = nil
        }
    }
    
    //build engine
    func buildProject() {
        
        //make sure engine is not running
        clearProject()
        
        //check to make sure engine is running
        guard startEngine() == true else { return }
        
        //set engine's current project
        currentProject = coreDataManager?.currentProject
        
        //initialize sequencer
    
        guard let engine = outputUnit?.engine else {
            return
        }
        sequencer = Sequencer(audioEngine: engine)
        
        //setup metronome
        setupMetronome()
        
        guard let tracks = currentProject?.tracks else { return }
        
        //setup track units
        for track in tracks {
            guard let theTrack = track as? Track else { return }
            guard let trackType = theTrack.trackType?.intValue else { return }
            
            switch trackType {
                
            //audio track
            case 0:
                if let player = AudioPlayerNode(url: theTrack.getAudioURL()) {
                    theTrack.audioPlayer = player
                }
                break
                
            //Instrument/Percussion Track
            case 1, 2:
                let sampler = AKMIDISampler()
                do {
                    try sampler.loadPath(theTrack.getSoundBankUrl().path)
                } catch {
                    print("Error loading sound for instrument/percussion track")
                }
                theTrack.samplerUnit = sampler
                break
                
            //Existing track
            case 3:
                break
                
            //Sampler track
            case 4:
                var audioFiles = [AKAudioFile]()
                for sampleURL in theTrack.samplesArray {
                    do {
                        //Use EZAudio to see if audio file loads
                        EZAudio.setShouldExitOnCheckResultFail(false)
                        if EZAudioFile(url: sampleURL) != nil {
                            let audioFile = try AKAudioFile(forReading: sampleURL)
                            audioFiles.append(audioFile)
                        }
                    } catch {
                        print("Error loading sound for sample track")
                    }
                }
                let sampler = AKMIDISampler()
                do {
                    try sampler.loadAudioFiles(audioFiles)
                } catch {
                    print("Error loading sampler track")
                }
                theTrack.samplerUnit = sampler
                break
            default:
                break
            }
        }
        
        // Build effects if any before connecting tracks to mixer and starting engine
        finishedBuildingEffects = {
            
            //connect mixer to output effects and output node
            self.connectMixerToOutput()
            
            //connect track units to effects and mixer
            self.connectTracksToMixer()
            
            //Build Sequence
            self.rebuildSequence()
            
            AudioEngine.sharedInstance().buildSoloTracks()
        }
        buildTrackEffects(forTrack: 0)
    }
    
    //sequencer
    
    func rebuildSequence() {
        
        guard let tracks = coreDataManager?.currentProject.tracks else { return }
        sequencer?.buildMidiFile(withMetronome: true)
        
        let isPlaying = self.isPlaying
        let currentPosition = self.getCurrentPositionInSeconds
        if isPlaying {
            pauseSong()
        }
        
        self.removeUnitsFromSequencer()
        sequencer?.loadMidiFile()

        for (index, track) in tracks.enumerated() {
            guard let track = track as? Track, let trackType = track.trackType?.intValue else { return }
            switch trackType {
            case 1,2,4:
                if let sequencer = sequencer, index < sequencer.tracks.count {
                    sequencer.tracks[index].destinationAudioUnit = track.samplerUnit?.samplerUnit
                }
                break
            default:
                break
            }
        }
        if let sequencer = sequencer, tracks.count < sequencer.tracks.count {
            sequencer.tracks[tracks.count].destinationAudioUnit = metronomeNode?.samplerUnit
        }
        if let sequencer = sequencer, let songLength = currentProject?.actualSongLengthInBeats?.doubleValue {
            for track in sequencer.tracks {
                if songLength > 1 {
                    track.isLoopingEnabled = true
                    track.loopRange = AVMakeBeatRange(0, songLength)
                }
            }
        }
        
        if isPlaying {
            playSong(atTime: CGFloat(currentPosition))
        }
    }
    
    //metronome
    func setupMetronome()  {
        metronomeNode = AKMIDISampler()
        do {
            if let url = Bundle.main.url(forResource: "metronome", withExtension: "sf2") {
                try metronomeNode?.loadPath(url.path)
            }
        } catch {
            print("Error loading metronome")
        }
    }
    
    func connectMetronomeToMixer() {
        //connect metronome to mixer
        if let metronome = metronomeNode, let mixer = mixer {
            metronome >>> mixer
        }
    }
    
    //mixer
    func connectTracksToMixer() {
        guard let mixer = mixer, let tracks = currentProject?.tracks else { return }
        
        //get first node from track based on type
        for track in tracks {
            guard let track = track as? Track,
                let trackType = track.trackType?.intValue else { return }
            
            var trackNode = AKNode()
            switch  trackType {
            case 0: //if audio file
                if let playerUnit = track.audioPlayer {
                    let playerNode = AKNode(avAudioNode: playerUnit, attach: true)
                    trackNode = playerNode
                }
            default:
                if let samplerUnit = track.samplerUnit {
                    trackNode = samplerUnit
                }
            }
            
            //connect any effects on track if any to the mixer if not connect first node directly to the mixer
            if let effects = track.effects, effects.count > 0 {
                var previousNode = trackNode.avAudioNode
                for effect in effects {
                    guard let effect = effect as? Effect, let effectNode = effect.unit else { break }
                    AudioKit.engine.attach(effectNode)
                    AudioKit.engine.connect(previousNode, to: effectNode)
                    previousNode = effectNode
                }
                AudioKit.engine.connect(previousNode, to: mixer.avAudioNode)
            } else {
                AudioKit.engine.connect(trackNode.avAudioNode, to: mixer.avAudioNode)
            }
        }
        connectMetronomeToMixer()
    }
    
    func connectMixerToOutput() {
        guard let effects = currentProject?.outputMixer?.effects, let mixer = mixer, let outputUnit = outputUnit else { return }
        var previousNode = mixer.avAudioNode
        for effect in effects {
            guard let effect = effect as? Effect, let effectNode = effect.unit else { break }
            AudioKit.engine.attach(effectNode)
            AudioKit.engine.connect(previousNode, to: effectNode)
            previousNode = effectNode
        }
        AudioKit.engine.connect(previousNode, to: outputUnit)
    }
    
    //effects build async so using recursion to let them build
    var finishedBuildingEffects: (()->Void)?
    func buildTrackEffects(forTrack trackIndex: Int) {
        guard let trackCount = currentProject?.tracks?.count,
            trackIndex < trackCount else {
                buildOutputEffects(effectindex: 0)
                return
        }
        buildEffect(forTrack: trackIndex, atIndex: 0)
    }
    
    func buildEffect(forTrack trackIndex: Int, atIndex effectIndex: Int) {
        guard let tracks = currentProject?.tracks,
            trackIndex < tracks.count,
            let track = tracks.object(at: trackIndex) as? Track,
            let effects = track.effects,
            effectIndex < effects.count,
            let effect = effects.object(at: effectIndex) as? Effect else {
                buildTrackEffects(forTrack: trackIndex + 1)
                return
        }
        effect.build({ (avAudioUnit) in
            self.buildEffect(forTrack: trackIndex, atIndex: effectIndex + 1)
        }) {
            track.removeEffectsObject(effect)
            self.buildEffect(forTrack: trackIndex, atIndex: effectIndex)
        }
    }
    
    func buildOutputEffects(effectindex: Int) {
        guard let effects = currentProject?.outputMixer?.effects,
            effectindex < effects.count,
            let effect = effects.object(at: effectindex) as? Effect else {
                finishedBuildingEffects?()
                return
        }
        effect.build({ (aavAudioUnit) in
            self.buildOutputEffects(effectindex: effectindex + 1)
        }) {
            self.currentProject?.outputMixer?.removeEffectsObject(effect)
            self.buildOutputEffects(effectindex: effectindex)
        }
    }
    
    func projectHasAudioTracks() -> Bool {
        guard let tracks = currentProject?.tracks?.array as? [Track] else { return false }
        for track in tracks {
            if track.trackType?.intValue == 0 {
                return true
            }
        }
        return false
    }
}

**Comment by robtize** [comment] 2018-04-07 18:42
This is all of the code in my audioengine file

**Comment by aure** [comment] 2018-04-07 22:09
I guess I would like to see whether this is truly the case in Xcode 9.3 as that is what AudioKit 4.2 was intended for and I'm not seeing it in my app that uses AKAppleSampler.  While the code above is useful (it looks fine by the way), really testing it would require a project and assembling one around this file is a lot of work. So, if you could provide even a private github link to test this out, that would be helpful.  I'll close the issue for now, but feel free to reopen with more info, especially once you're on Xcode 9.3.

**Closed by aure** 2018-04-07 22:09 UTC
