### ISSUE TITLE
AVAudioSessionErrorInsufficientPriority

### ISSUE THREAD

**Issue by dkun7944** [audiokit/AudioKit#739] opened 2017-02-10 11:55 UTC
Some of my users are getting AVAudioSessionErrorInsufficientPriority when my app calls AudioKit.start(). I can't seem to replicate this. How should I keep the app from crashing?

**Comment by aure** [comment] 2017-02-11 12:10
I've never even heard of priority in terms of session management.   Can you (or someone watching) do the research required to get this sorted?

**Comment by dkun7944** [comment] 2017-02-11 15:36
Google search yields virtually nothing useful, except that a phone call might while trying to set session category might be the culprit. 

Can someone attempt to call AudioKit.start() while on a phone call and see what happens? (my devices have no SIM cards so I can't test this)

Should be as easy as [cloning this](https://github.com/dkun7944/pitch-ios) and running while in a phone call.

**Comment by aure** [comment] 2017-02-21 23:30
Sorry its taken so long to get to this issue (as well as others).  But now that I try the link you have it comes up as missing.  I think you've closed the source to the Pitch project.  I'll close the issue for now, but reopen at will, with new information.

**Closed by aure** 2017-02-21 23:30 UTC

**Comment by mike-normal13** [comment] 2017-10-18 00:29
First off, Thank you for AudioKit Aure! I would never have figured out audio fades without it! 

I'm writing a Sampler App for iOS using AVFoundation. Without boring you with too much detail, various audio route changes require me to make adjustments to my sound graph, e.g. sound coming out of my phone's Speaker is mono, while sound coming out of my headphone jack is stereo. A scenario of switching mixer nodes from mono to stereo format requires me to restart my AVAudioEngine member. 

Much like plugging in headphones triggers my AVAudioSessionRouteChange observer, so does an incoming phone call. The problem is that if you call start() on you’re engine while a call is waiting to be answered or dismissed then you get the AVAudioSessionErrorInsufficientPriority exception. 

The way I am currently handling this is that if I nab AVAudioSession.sharedInstance().currentRoute in my handleAduioRouteChange(notification: Notification) method while a phone call is waiting to be answered or declined, the current route will have 0 outputs. So if my current route has 0 outputs I just return, without disconnecting and reconnecting my audio graph and then finally calling start() on my engine. This is a bit of a hack, but my app is no longer crashing. It works for now.

Attached Line 293.

Thanks Again! If I ever figure out on the spot fades, I will show the world.


[MaserSoundMod.txt](https://github.com/AudioKit/AudioKit/files/1393050/MaserSoundMod.txt)

**Comment by mike-normal13** [comment] 2017-10-18 00:47
Unfortunately, with my 6s, my above offered solution only works if the phone is in silent mode while the phone receives the call. I'm still grinding.
